---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gitea
  - gitea-actions
  - media-server
  - miasma
  # - mitmproxy
  # - pds
  - redirector
  # - searxng
  - vaultwarden
  - zeroclaw
