---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    secret.reloader.stakater.com/reload: forgejo-admin,forgejo-inline-config
  labels:
    app.kubernetes.io/instance: forgejo
    app.kubernetes.io/name: forgejo
  name: forgejo
  namespace: forgejo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: forgejo
      app.kubernetes.io/name: forgejo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: forgejo
      labels:
        app.kubernetes.io/instance: forgejo
        app.kubernetes.io/name: forgejo
    spec:
      containers:
        - env:
            - name: GITEA_APP_INI
              value: /data/gitea/conf/app.ini
            - name: GITEA_CUSTOM
              value: /data/gitea
            - name: GITEA_TEMP
              value: /tmp/gitea
            - name: GITEA_WORK_DIR
              value: /data
            - name: HOME
              value: /data/gitea/git
            - name: SSH_LISTEN_PORT
              value: !!str 2222
            - name: SSH_PORT
              value: !!str 22
            - name: TMPDIR
              value: /tmp/gitea
          image: codeberg.org/forgejo/forgejo:15.0.1-rootless
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 10
            initialDelaySeconds: 200
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: http
            timeoutSeconds: 1
          name: forgejo
          ports:
            - containerPort: 2222
              name: ssh
            - containerPort: 3000
              name: http
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 4m
              memory: 93Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /tmp
              name: temp
      initContainers:
        - command:
            - /usr/sbin/init_directory_structure.sh
          env:
            - name: GITEA_APP_INI
              value: /data/gitea/conf/app.ini
            - name: GITEA_CUSTOM
              value: /data/gitea
            - name: GITEA_TEMP
              value: /tmp/gitea
            - name: GITEA_WORK_DIR
              value: /data
          image: codeberg.org/forgejo/forgejo:15.0.1-rootless
          imagePullPolicy: IfNotPresent
          name: init-directories
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /tmp
              name: temp
            - mountPath: /usr/sbin
              name: init
        - command:
            - /usr/sbin/configure_environment.sh
          env:
            - name: GITEA_APP_INI
              value: /data/gitea/conf/app.ini
            - name: GITEA_CUSTOM
              value: /data/gitea
            - name: GITEA_TEMP
              value: /tmp/gitea
            - name: GITEA_WORK_DIR
              value: /data
          # envFrom:
          #   - configMapRef:
          #       name: forgejo-app-ini-env
          #   - secretRef:
          #       name: forgejo-app-ini-env
          image: codeberg.org/forgejo/forgejo:15.0.1-rootless
          imagePullPolicy: IfNotPresent
          name: init-app-ini
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /env-to-ini-mounts/inlines/
              name: inline-config-sources
            - mountPath: /usr/sbin
              name: init
            - mountPath: /tmp
              name: temp
        - command:
            - /usr/sbin/configure_gitea.sh
          env:
            - name: GITEA_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: forgejo-admin
            - name: GITEA_ADMIN_PASSWORD_MODE
              value: keepUpdated
            - name: GITEA_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: forgejo-admin
            - name: GITEA_APP_INI
              value: /data/gitea/conf/app.ini
            - name: GITEA_CUSTOM
              value: /data/gitea
            - name: GITEA_TEMP
              value: /tmp/gitea
            - name: GITEA_WORK_DIR
              value: /data
            - name: HOME
              value: /data/gitea/git
          image: codeberg.org/forgejo/forgejo:15.0.1-rootless
          imagePullPolicy: IfNotPresent
          name: configure-gitea
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /tmp
              name: temp
            - mountPath: /usr/sbin
              name: init
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 60
      volumes:
        - name: config
          secret:
            defaultMode: 110
            secretName: forgejo
        - name: data
          persistentVolumeClaim:
            claimName: forgejo-data
        - configMap:
            defaultMode: 110
            name: forgejo-init
          name: init
        - name: inline-config-sources
          secret:
            secretName: forgejo-inline-config
        - emptyDir: {}
          name: temp
