---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: forgejo
    app.kubernetes.io/name: forgejo
  name: forgejo-http
  namespace: forgejo
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 3000
  selector:
    app.kubernetes.io/instance: forgejo
    app.kubernetes.io/name: forgejo
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: forgejo
    app.kubernetes.io/name: forgejo-valkey
  name: forgejo-valkey
  namespace: forgejo
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: redis
      port: 6379
  selector:
    app.kubernetes.io/instance: forgejo
    app.kubernetes.io/name: forgejo-valkey
  type: ClusterIP
