---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  imageRepositoryRef:
    name: vaultwarden
  policy:
    semver:
      range: ">=1.35.0 <2.0.0"
