---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app.kubernetes.io/instance: vaultwarden
    app.kubernetes.io/name: vaultwarden-data
  name: vaultwarden-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    name: vaultwarden-data
    namespace: vaultwarden
  iscsi:
    fsType: btrfs
    iqn: ***REMOVED***
    lun: 15
    targetPortal: ***REMOVED***
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
