---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app.kubernetes.io/instance: vaultwarden
    app.kubernetes.io/name: vaultwarden
  name: vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    name: vaultwarden
    namespace: vaultwarden
  csi:
    driver: csi.san.synology.com
    fsType: btrfs
    volumeAttributes:
      dsm: ***REMOVED***
      location: /volume1
    volumeHandle: pvc-603f3218-536c-412c-acc0-ab33562cd2bc
  persistentVolumeReclaimPolicy: Retain
  storageClassName: synology-iscsi-storage
  volumeMode: Filesystem
