apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  labels:
    app.kubernetes.io/instance: vaultwarden
    app.kubernetes.io/name: vaultwarden-docker
  name: vaultwarden-docker
  namespace: vaultwarden
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:6RaQwXGEZ6lQpg==,iv:OmTDLWFluVMV7U/AdaPYYu3imUBniognrVAhFm9L9v4=,tag:KK9/+ichfrGBSWW1WYw76A==,type:str]
      stringData:
        .dockerconfigjson: ENC[AES256_GCM,data:G06sTCxlNzaUOQsWreacltoVrojY4FhWLeH9HyGx/7wDq52ZLLX9VQVuHbs5xtN4BdeS/Q9yCLuSqM2JwNexkAGaxfyF3tlPwmKlnkEAl2T1ZpK8cQa93AsGcomrXEL640nuIkpkdNJYHOSXyxEUitlHVgdErCMHhZN1i+I0ObQ4FBFQGIFouwMdlvpgMKlGIDe5Jk4=,iv:7BDtz48Yz7SgFlOaHlZuYK3WPV3v0EP9oyhIHeFAFcs=,tag:f4pAuNAiV34xt5sXik86CA==,type:str]
      type: ENC[AES256_GCM,data:OOm5eCIk0LXbxxyhoY4g/N5eEJrHjzWcM320SK9/,iv:fFlP1okBTwC+CjlwVd8fMJ33/fPqu8nUDhTpU9v4LTg=,tag:d5U3IUTPRD//YMO5YXnLGw==,type:str]
sops:
  age:
    - recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITlVjQ3RDb20zZ1Q3RzU4
        OXB5ZXdidDdmNWxESE5oaGpiWXZSc0NvUFI4CjF0b2JaVFU5eTZKbTlFTjNiUkJv
        R2VYNUUyc3hKUkRaeGVPUWMyamRRT28KLS0tIGlHazRDcG5BRlhOc1RvS1oxMVAy
        ZVk2UFJkcldMOFN2MkpiV29rVEFxRUEKiIfZijzhKP+SVmz14dLyNzCx2DIwUYXk
        48bk3EOoyJqcYPXIYUYM4QVG+T5ah6ovMlMT/wU4HlM5bTcAQklxBQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T00:00:16Z"
  mac: ENC[AES256_GCM,data:Mw3VIhygfZzia9YwwMGrmjpbL4TGsiSCMDddiz5VR6SHwhoeyuyd64JxwZk7Zn4iVGZa4gam8gEwKFmWUqGMytwovu9vVHyd/SNcie0hmcTXNKDqn7kt2FX9kCVRDqSYh7SKp9lswJRjuDMRtJXdmauHi+vcsXhGUueeSzsMddk=,iv:y2WRa1i4u5A9TJVcK1J0grakty7AmFou9bEwOnWeqfI=,tag:R0Sh23HGtwGHnvqR4l8Oyw==,type:str]
  encrypted_suffix: Templates
  version: 3.12.1
