---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: llama-cpp
  namespace: llama-cpp
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`llama.example.com`)
      middlewares:
        - name: ip-allowlist
        - name: security-headers
      services:
        - name: llama-cpp
          port: 80
  tls:
    secretName: llama-cpp-tls
