---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-cpp-models
  namespace: llama-cpp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: llama-cpp-models
