---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: llama-cpp-models
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /var/lib/llm-models
    type: DirectoryOrCreate # FIXME
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
