---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/pds

configMapGenerator:
  - behavior: merge
    literals:
      - PDS_HOSTNAME=pds.osborn.io
    name: pds-env
    namespace: pds

secretGenerator:
  - envs:
      - configs/pds-env.sops.env
    name: pds-env
    namespace: pds

patches:
  - patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`pds.osborn.io`) || Host(`nick.pds.osborn.io`)
      - op: add
        path: /spec/tls/domains
        value:
          - main: pds.osborn.io
            sans:
              - nick.pds.osborn.io
    target:
      kind: IngressRoute
      name: pds
      namespace: pds
