apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: pds
  namespace: pds
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:2zVOiKEljQ==,iv:zDzo/cF7STYmAOoe+CDj7PfWr7f0Po1uJIavQ8IxtPM=,tag:LHCuHeoli5k79Zd0zBKIfA==,type:str]
      stringData:
        PDS_ADMIN_PASSWORD: ENC[AES256_GCM,data:HUbUnghRJWAdhYy/EB+L92BDwyx+eIANUq6+TBqHADs=,iv:BjKjFKVR/TM15+VPnT3QrA7PW2v2+StFPhqh5Fo/7Qk=,tag:ki/cgkyJ1nno910F357AKw==,type:str]
        PDS_JWT_SECRET: ENC[AES256_GCM,data:ODPucpz4ScptfsT3R0OvR6U3pYjKr+E0wPs6IBoxPO4=,iv:a9POmzEvRHMTJaXrUEWGDvvfieQdrkxogGlDQ0FRHcw=,tag:283g/PJFOII//tcJoTysAQ==,type:str]
        PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX: ENC[AES256_GCM,data:5Oa1zEBSZTcNKCHqaNLFEXO7bu1+3VGiemRNWzT6Xy/hlFNGBfxedzefpO3hrKPoOMF3QsWs3vc0gLQF892+Ng==,iv:lkN9BHCfyAFq2TmlUvztN5rcZc/djpBnSfY4hEua42s=,tag:tFybGxDbKiYbpJcOBFwgdQ==,type:str]
sops:
  age:
    - recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RFFsK2xlMUlDTklPUmVM
        RnJaaXZLTjh3VWZvVXhadFF4SXBOczNrV0M4Cmk3eVZDUStjb2JWM1gzaFFBeGFF
        clBpZU8xVTFrOVhnQTY4VCtDM3hkaTQKLS0tIDA3YjF1VDhLNkpXb2NsREJEMlRn
        UHJVb0w0SjkyY3pJcUJjMjNQVUJIdlkKr/iu2QIdmEsQBlPGgAJEDmfdC5GXiGHk
        NqWOaDJN5OLc69RChUmpngXuzLuXRGFfL6EqhBZUIw3EjxC85OMVkg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-14T08:25:00Z"
  mac: ENC[AES256_GCM,data:xChGLX96VxAz8NNKNmxDTGXDuy4gMILr0HTks4HO69zOCYaUlmGo+3F6+0OygfXpZcnSZtV9IjYAiRMYo2E6ivCqHdXkiihZrOTGb4QBJL9d0ejNLGW858xr+tVwBuxpPoRj8Htkl32w2vMakCnnbJezera3QlwSK4p9hsY6e5k=,iv:oqP48jt9P8kF7v7zqU7RjAc9v75ffeV9K+hBkVtYdko=,tag:pN9KSJsoyCnZ7mgIEcJJ4Q==,type:str]
  encrypted_suffix: Templates
  version: 3.12.2
