---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/name: gitea-data
  name: gitea-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  claimRef:
    name: gitea-data
    namespace: gitea
  iscsi:
    fsType: btrfs
    iqn: ${ISCSI_IQN}
    lun: 2
    targetPortal: ${ISCSI_TARGET_PORTAL}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
