---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/miasma

patches:
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - miasma.osborn.io
    target:
      kind: Certificate
      name: miasma
      namespace: miasma
  - patch: |-
      - op: replace
        path: /spec/hostnames
        value:
          - tombstone.osborn.io
    target:
      kind: HTTPRoute
      name: miasma-nginx
      namespace: miasma
