pid /tmp/nginx.pid;

events {
  worker_connections 768;
}

http {
  access_log /var/log/nginx/access.log combined;

  client_body_temp_path /tmp/client_temp;
  fastcgi_temp_path /tmp/fastcgi_temp;
  proxy_temp_path /tmp/proxy_temp;
  scgi_temp_path /tmp/scgi_temp;
  uwsgi_temp_path /tmp/uwsgi_temp;

  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  # Reserve 8MB memory for tracking user agents
  limit_req_zone $http_user_agent zone=miasma:8m rate=1r/s;

  server {
    listen 8080 default_server;
    server_name _;
    server_tokens off;

    location /healthz {
      access_log off;
      add_header Content-Type text/plain;
      return 200 "OK\n";
    }

    location ~ ^/miasma($|/.*)$ {
      limit_req_status 429;
      limit_req zone=miasma burst=5 nodelay;
      proxy_pass http://miasma:80;
    }

    location / {
      root /data/tombstone.osborn.io-main/public;
    }
  }
}
