---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/media-server
  - resources/ingressroute.yaml

secretGenerator:
  - files:
      - config.yaml=configs/bazarr.yaml
    name: bazarr-config
    namespace: media
  # - files:
  #     - config.xml=configs/lidarr.xml
  #   name: lidarr-config
  #   namespace: media
  - files:
      - nzbget.conf=configs/nzbget.conf
    name: nzbget-config
    namespace: media
  - files:
      - config.xml=configs/prowlarr.xml
    name: prowlarr-config
    namespace: media
  - files:
      - config.xml=configs/radarr.xml
    name: radarr-config
    namespace: media
  - files:
      - configs/recyclarr.yml
    name: recyclarr-config
    namespace: media
  - envs:
      - configs/recyclarr.env
    name: recyclarr-env
    namespace: media
  - files:
      - config.xml=configs/sonarr.xml
    name: sonarr-config
    namespace: media

patches:
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - bazarr.${DOMAIN_NAME}
    target:
      kind: Certificate
      name: bazarr
      namespace: media
  # - patch: |-
  #     - op: replace
  #       path: /spec/dnsNames
  #       value:
  #         - lidarr.${DOMAIN_NAME}
  #   target:
  #     kind: Certificate
  #     name: lidarr
  #     namespace: media
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - muxarr.${DOMAIN_NAME}
    target:
      kind: Certificate
      name: muxarr
      namespace: media
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - nzbget.${DOMAIN_NAME}
    target:
      kind: Certificate
      name: nzbget
      namespace: media
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - ombi.${DOMAIN_NAME}
    target:
      kind: Certificate
      name: ombi
      namespace: media
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - prowlarr.${DOMAIN_NAME}
    target:
      kind: Certificate
      name: prowlarr
      namespace: media
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - radarr.${DOMAIN_NAME}
    target:
      kind: Certificate
      name: radarr
      namespace: media
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - sonarr.${DOMAIN_NAME}
    target:
      kind: Certificate
      name: sonarr
      namespace: media
  - patch: |-
      - op: add
        path: /spec/template/spec/securityContext/fsGroup
        value: 100
      - op: add
        path: /spec/template/spec/securityContext/runAsGroup
        value: 100
      - op: add
        path: /spec/template/spec/securityContext/runAsUser
        value: 1026
    target:
      kind: Deployment
      namespace: media
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: PGID
          value: !!str 100
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: PUID
          value: !!str 1026
    target:
      kind: Deployment
      name: muxarr
      namespace: media
