---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    app.kubernetes.io/instance: rsshub
    app.kubernetes.io/name: rsshub
  name: rsshub
  namespace: rsshub
spec:
  hostnames:
    - rsshub.example.com
  parentRefs:
    - name: gateway
  rules:
    - backendRefs:
        - name: rsshub
          port: 80
      filters:
        - extensionRef:
            group: traefik.io
            kind: Middleware
            name: security-headers
          type: ExtensionRef
      matches:
        - path:
            type: PathPrefix
            value: /
