---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/social
  - resources/persistentvolume.yaml
  - resources/persistentvolumeclaim.yaml

secretGenerator:
  - envs:
      - configs/pds.env
    name: pds-env
    namespace: social

patches:
  - patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`social.osborn.io`) || Host(`nick.social.osborn.io`)
      - op: add
        path: /spec/tls/domains
        value:
          - main: social.osborn.io
            sans:
              - nick.social.osborn.io
    target:
      kind: IngressRoute
      name: social
      namespace: social
