---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: meetup
  namespace: mitmproxy
spec:
  dnsNames:
    - api.meetup.com
  duration: 168h
  issuerRef:
    kind: ClusterIssuer
    name: ownca
  renewBefore: 8h
  secretName: proxy-meetup-tls
