# yamllint disable rule:line-length
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: !!str true
  name: mitmproxy
  namespace: mitmproxy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: mitmproxy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      # annotations:
      #   kubectl.kubernetes.io/default-container: nginx
      labels:
        app: mitmproxy
    spec:
      containers:
        - command:
            - mitmweb
            - --web-host=0.0.0.0
          image: docker.io/mitmproxy/mitmproxy:12.2.1
          # livenessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /
          #     port: http-web
          #     scheme: HTTP
          #   periodSeconds: 10
          #   successThreshold: 1
          #   timeoutSeconds: 1
          name: mitmproxy
          ports:
            - containerPort: 8080
              name: http-proxy
              protocol: TCP
            - containerPort: 8081
              name: http-web
              protocol: TCP
          # readinessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /
          #     port: http-web
          #     scheme: HTTP
          #   periodSeconds: 10
          #   successThreshold: 1
          #   timeoutSeconds: 1
          resources: {}
          # requests:
          #   cpu: 1m
          #   memory: 11Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            # - mountPath: /etc/nginx/nginx.conf
            #   name: config
            #   subPath: nginx.conf
            # - mountPath: /etc/nginx/redirect.js
            #   name: config
            #   subPath: redirect.js
            - mountPath: /home/mitmproxy/.mitmproxy
              name: data
            - mountPath: /tmp
              name: tmp
      imagePullSecrets:
        - name: docker-hub
      securityContext:
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      volumes:
        # - emptyDir: {}
        #   name: cache
        # - configMap:
        #     name: mitmproxy-nginx
        #   name: config
        - emptyDir: {}
          name: data
        - emptyDir:
            medium: Memory
            sizeLimit: 1Mi
          name: tmp
