---
apiVersion: v1
kind: Secret
metadata:
  name: dockerconfig
  namespace: mitmproxy
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:yljDLxRSjUNiByoU0ktOpBS5MTJx00OrBM4RiVn5UTDmyZn3r7RqBKep+eRSfyVyZN2BnGYdqgeQdywFsHqcdOEVsaIHjU8pyGW9hhNvZtb+KbePwWOyTtyy04Q63GliU2j+Whu1beIu1Y+qcClYIYhuIQoVm/ARfIXVStZrEPJs5bkehJcWqnSL1LgtpMr1t9+/vLY=,iv:TM+nwrHTXZl//Zdt5fhxYWjaaQ/tzDHWdCWLfLWmgQM=,tag:yqQSTB5s0fBJeRiwyaH1uQ==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMUtsRGYzUVUxalJKaWVJ
        UjdKZUYraTlZVi9CcDV1ZDltOUo2bzZwNlM4CmNlOEpsTzFDVHY2aDlMMkptTVow
        M1paS09TMmh4anBsV1NSN0VnSkl6d0UKLS0tIGRETUlIcXpCZEtucitJbVorTjZG
        d2tFN0wwU2o1T3pTUmNQT2R6S01WTEEK9nULiCwgcN5H0HIRPZ+Ky7rx4Ntg2rqH
        6KMn8vo3/6/JhHoX+oGVuuCH/J2ro+MyCYXiXG3+WhauVt2jmocm8w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-23T05:56:12Z"
  mac: ENC[AES256_GCM,data:CoZbFg3HgYManXeEkUOg+wByp7Glh/tdytOMKlis9L2P1/6Nlu1J2CuJTskcKINrv2RaMFxwARXC32N9cpBXZLwiUStDYOTm38nKIMo2xsXCZFMp4eiW9pk+T19gySe5GHTwUGiGY9bZZG0m+DOv8S4UCiFYUTtNG70V7yln0G8=,iv:cWC6PnDPQhN3qYYvnQEc6jqXMSXqYHWXfTEtZBOQF/k=,tag:4QVU7OI2ix7BqI8CGStl+Q==,type:str]
  version: 3.13.1
