---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: mitmproxy
    app.kubernetes.io/name: mitmproxy
  name: mitmproxy
  namespace: mitmproxy
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http-proxy
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: http-web
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app.kubernetes.io/instance: mitmproxy
    app.kubernetes.io/name: mitmproxy
  type: ClusterIP
