---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/search

secretGenerator:
  - envs:
      - configs/searxng.env
    name: searxng-env
    namespace: search

patches:
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - search.${DOMAIN_NAME}
    target:
      kind: Certificate
      name: search
      namespace: search
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SEARXNG_BASE_URL
          value: https://search.${DOMAIN_NAME}
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: TZ
          value: Europe/London
    target:
      kind: Deployment
      name: searxng
      namespace: search
  - patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`search.${DOMAIN_NAME}`)
    target:
      kind: IngressRoute
      name: search
      namespace: search
