---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: miniflux
    app.kubernetes.io/name: miniflux
  name: miniflux
  namespace: miniflux
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: miniflux
    app.kubernetes.io/name: miniflux
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: miniflux
    app.kubernetes.io/name: postgres
  name: postgres
  namespace: miniflux
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app.kubernetes.io/instance: miniflux
    app.kubernetes.io/name: postgres
  type: ClusterIP
