---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/homebridge

secretGenerator:
  - files:
      - configs/config.json
    name: homebridge-config
    namespace: homebridge

patches:
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - homebridge.${DOMAIN_NAME}
    target:
      kind: Certificate
      name: homebridge
      namespace: homebridge
  - patch: |-
      - op: add
        path: /spec/template/spec/securityContext/fsGroup
        value: 100
      - op: add
        path: /spec/template/spec/securityContext/runAsGroup
        value: 100
      - op: add
        path: /spec/template/spec/securityContext/runAsUser
        value: 1026
    target:
      kind: Deployment
      namespace: homebridge
  - patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`homebridge.${DOMAIN_NAME}`)
    target:
      kind: IngressRoute
      name: homebridge
      namespace: homebridge
