# yamllint disable rule:line-length
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: redirector
  namespace: redirector
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        chore(redirector): update {{ range .Changed.Changes }}{{ .NewValue }}{{ end }}
        {{ range .Changed.Changes }}
        - {{ .OldValue }} -> {{ .NewValue }}
        {{- end }}
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  update:
    path: ./apps/base/redirector/resources
    strategy: Setters
