---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/instance: tt-rss
    app.kubernetes.io/name: tt-rss
  name: tt-rss
  namespace: rss
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: tt-rss
      app.kubernetes.io/name: tt-rss
  policyTypes:
    - Ingress
