---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: tt-rss
    app.kubernetes.io/name: tt-rss
  name: tt-rss
  namespace: rss
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 80
  selector:
    app.kubernetes.io/instance: tt-rss
    app.kubernetes.io/name: tt-rss
  type: ClusterIP
