---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: miasma
  namespace: miasma
spec:
  imageRepositoryRef:
    name: miasma
  policy:
    semver:
      range: ">=0.2.0 <1.0.0"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: nginx
  namespace: miasma
spec:
  filterTags:
    extract: $version
    pattern: ^(?P<version>\d+\.\d+\.\d+)-alpine-otel$
  imageRepositoryRef:
    name: nginx
  policy:
    semver:
      range: ">=1.31.0 <2.0.0"
