apiVersion: v1
kind: Secret
metadata:
  name: dockerconfig
  namespace: miasma
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:FvtsYuBhaV4VggjOPl9zxbJR67jGp7xdh4bGyp2AireMoaWDPKrXGIXtqsxfSBqnTiSTiEtTbwIy9qYwZCGy7xZ2hj6XdoEbTuq2R+NIggq6XxUR+eFcOu2E63h8ch4xBbhou2eVf5koqqk5RJVSVnIA4U5STXE3Mqpuu1nPAgNqhomnDx7MKHlEfXIAv23h4jeXZAw=,iv:jlftjyIc1cOjAxkaLB5oQiPgmseeSn9mRfb+PVDChkw=,tag:0maKAjvWvk0KpWdzcXm2kw==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdjZZS0NBMkFCYnc3L0FF
        TS9oc21GYm4wV3Q1STAvZDVSQjNNSGladzJnClF0b2x1Y3BLdHlpUFV1akRjSjhX
        OWJHaW9URTU5UlZlUzlpbkF0VXRYa3MKLS0tIGxkd0tCMWZtdjg2djlVdlB2SE5H
        eUtlNkZOelJUb01zdXQxUVJJbWN4UlkKoGmr0u7bJ2jlWpR7szhKSg/BtNL01XTY
        +wSyEhqePnge3OB3+gwXHJ17ha647ChBwbpByK54Sya2BEe5LUSZHg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-13T18:17:14Z"
  mac: ENC[AES256_GCM,data:16f51RG+N1WkaiRrDOqM5wCqAPq+MSdR+n78h7VUk8ymLc79Vsr/C1Q+w3hVrZlktows3qH4zyscH1H7b2VVQd2+4os6PGbSnau4ZRmHYkzCEajItNVZlTwvI0W60DOKh31g9ZuevX2KexYPHbL92Pu5tAYNtKm6QoECSH4YcdY=,iv:/hinBhC3v6dF9x88GDaZCNLAa7QyfCBuPdexQRxFDno=,tag:SkJk0mMXq6XXDSbh0nvN0w==,type:str]
  version: 3.13.0
