apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: miasma-docker
  namespace: miasma
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:7vthF3KB9HhJWQ==,iv:hl6FR/lYLYWgu+c54sGn8hq6oWaT/PgAGQHR7BZ/vZo=,tag:I4r4tpnGjp0mcY+EpE903w==,type:str]
      stringData:
        .dockerconfigjson: ENC[AES256_GCM,data:QELRjwrqhFnBlzXVpAiTNcdxMkBnf1j5CNBXaK55Z4ch9HC1cOzf7MUjya7gGU/DWVMrjDRBxGM3GxoCnNvUSHXH2QjArNLH2EvAhEFsq8ZjziFdYPwXTpkThWk8r+nalhJ9VYa2100iCe9nx2ZS0hHh9oh8RqTHhQpNLto0UbXPez6YC3GGG0fZvZjzvZmLZMa3Ql0=,iv:YfyZXtnC8J8m5WfpLeqZi36k+hnKKa4ba4uZSK+Bl88=,tag:wd7Px1nKlMyBxFPk9E0FBQ==,type:str]
      type: ENC[AES256_GCM,data:R23G5GpjbSuM2YmmUqVRwhwns5eAI6Kv2MAoK+Vr,iv:ncQRR/nynSjLXqBKWDj863opBfhuBPcAXzBP5YTcE4U=,tag:dbVQbEW7iMqn5gaFuNBdpQ==,type:str]
sops:
  age:
    - recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOV1BPQ0pMajBQZitVdnRo
        NTRLQ3RoNTl6dk5QQ2I2UTVSYitweGNMOG5ZCk5EWDE3Uit5VHMzWldrWjJpUEd0
        OXZzL09NeXorVkdkeEZPRjVCMDVJMGcKLS0tIGpESFBGNzMvcFVySnBXOXE4R1Jv
        bTdqZ3Nka25vR1l6aEF1M0hsVDU2VEUK6oHPfUpVgVCyLwQ4SMGDL84eGQ4lTk/G
        /93iApK2WUrvkJv+f2NkgR5xxazQhloWn9QroWMXg3EmF9a3gaSvig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T09:27:49Z"
  mac: ENC[AES256_GCM,data:hHM4mDO8C7/JDiH+zBvB30WRLirjqzXzYPJEF27WtkekDnNjWDrtR8xahDeyRCw8g2cSQP0tBoFRivWbID3Sj0NRh0QwkFHjBVVfy1vnKQW1/RirnAbcQDdQ+QR9+o55jjuYGqsLTFEgLAMRHg55E8qcsK1dmx25PgUGbgt7M/Y=,iv:7rc1eo3Pn/kAFsUpNowtPePWfIuyOlDxQAQVqmLT2BE=,tag:obtNsus0YbIw1MxVhVYZwQ==,type:str]
  encrypted_suffix: Templates
  version: 3.12.2
