---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/vaultwarden
  - resources/persistentvolume.yaml
  - resources/persistentvolumeclaim.yaml

secretGenerator:
  - behavior: merge
    envs:
      - configs/vaultwarden.env
    name: vaultwarden-env
    namespace: vaultwarden

patches:
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - passwords.${DOMAIN_NAME}
    target:
      kind: Certificate
      name: vaultwarden
      namespace: vaultwarden
  - patch: |-
      - op: replace
        path: /spec/hostnames
        value:
          - passwords.${DOMAIN_NAME}
    target:
      kind: HTTPRoute
      name: vaultwarden
      namespace: vaultwarden
