---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-local
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            ipBlocks:
              - ***REMOVED***
              - ***REMOVED***
              - ***REMOVED***
              - ***REMOVED***
            notIpBlocks:
              - ***REMOVED***
              - ***REMOVED***
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: ingress
