apiVersion: v1
kind: Secret
metadata:
  labels:
    reconcile.fluxcd.io/watch: Enabled
  name: vaultwarden-env
  namespace: vaultwarden
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:x98+b62Ig/TmcylqiYbCkG5+XJdrZouGLIytYnJzE/QFcGwLkXKNlCHxmxAA4LOf0XeNDKLjYHBt02UfXROtC5b+V40eH4txRhlzsYmyBmbC6ahjPRtkFPdieJlRxSMMgkqCCuU+NhO2YW/N+xYiK6eyM2fVAA==,iv:d8c4JprhbA8ce+VHOVAoJZuqr9+4+BwERelvK7LPEQo=,tag:O3tgolkcdsv5tS5bHPGaUQ==,type:str]
  PUSH_INSTALLATION_ID: ENC[AES256_GCM,data:Lo6VfLzt8n0tDb4q3sRWbyqvdGGGsj+e63WwXFEaXb0ejZkN,iv:qebI1X5SC8VXJznPFc4dJt7s2MmbcImlwsdHAohUP8U=,tag:Cb7xIpZXQx7MOdJUZadnug==,type:str]
  PUSH_INSTALLATION_KEY: ENC[AES256_GCM,data:l9tDL6rbr9WQaAxwTotMoABY1DY=,iv:8/oofkLkgajolhbpwnJFomzZWcMi+m3OeE8tZXNri1w=,tag:H0MamQlO1N0kadaRQbwuuQ==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbUVFdTY4KzFmZVV3T0tt
        VnZXZWJaY3ZITERUMXB4ZWY3aktzeWVIcHdvCnVLQlA4QjRENFc3cnI2dWp5akE0
        U0NoTWpLdTRxb25tUjR2akZKVHJMZVUKLS0tIEw4azNlOUh3NkpGVWkzVGhPVi90
        dEptcHlDMHV1ZHRscHpDMzgyczF1d28KzVKkkCddi9PC3U+p01LwMVXhjWrnixDz
        EVdQOJXy3hj17B8hF0Ky4zSJg/WSG0RGVhgqizu85qwXcUSmCYbKZw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-11T14:55:35Z"
  mac: ENC[AES256_GCM,data:yooPDmqyXJPwcwFMXSxIXUcz6mFib1XqzH1W9q7nN9X3yNP03zOaEFwTnQyjrqv+UhF1TlCqUJ5NjxcATw+Qg9Cn8GbnhmNHSqpXnrujk2Gk4Ddhv6JzXHC1SYMVBf/Q9nCEoDm+1K2M8d/1H2srNp8pRUudtY7+hW4DYTxFiFg=,iv:Sa4/1n3v/TIK0etvG3FsTKpksP1yAnuAcFd0QB2d/o8=,tag:z26giZjoZm8peIvaLXm9FA==,type:str]
  version: 3.13.0
