apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:rT4dPMRj4iWQ81HM2VDr,iv:s6dMPUApOGlGmkcgrK9HtysecVLwy0Z5qfFy6yvr7ys=,tag:ooV0u6mJgMSpjRyqG1e2vg==,type:str]
      type: ENC[AES256_GCM,data:qFAb/rfN,iv:rB6H5m9GJO0TA//J19GexMw3Cw+mm/tnIzLiWOjygEs=,tag:YQCSsi1u+iUs4V+xVfo2vA==,type:str]
      stringData:
        ADMIN_TOKEN: ENC[AES256_GCM,data:FoUpw7N/z6yii5PVgwTihAx8NVNH59+RspmdiitfylMFaBNtB6CafyCSKp9ePXJCtM7XrXHtZq+DBTZD2/UuCiFU0E5X9KtKF4HdOHmxSJWW6cncz1Oo52fbVxumktJ4mk6FrQaT1vaE6pepgI5sgA90QwPY8A==,iv:9rTBpU3KSygs4rdvnTyH0evJ7nv9xaRsvOyWsdXtLs8=,tag:zKgDaNRwSrNsEBComD8inQ==,type:str]
        PUSH_INSTALLATION_ID: ENC[AES256_GCM,data:dUXqSjVyrGmkq7r3Iq2xpeKXsAKkZ7GmR/48el5PRWZuZ+OZ,iv:0u8Ps0LLQo/zSJFBPtL49KskYxicx30jJ8lfqV3JrjA=,tag:qY+lDhnTRAeLwRN8HYP/SQ==,type:str]
        PUSH_INSTALLATION_KEY: ENC[AES256_GCM,data:YK+oTViP+G2/Fr7fhEW9zH5SOUo=,iv:rD9ZVoDSbCRzDftK5uapHDWCM3PElN/U5wdH+lkIwyU=,tag:wGHQToRjn6ki1u6wN2a07Q==,type:str]
sops:
  age:
    - recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RFFsK2xlMUlDTklPUmVM
        RnJaaXZLTjh3VWZvVXhadFF4SXBOczNrV0M4Cmk3eVZDUStjb2JWM1gzaFFBeGFF
        clBpZU8xVTFrOVhnQTY4VCtDM3hkaTQKLS0tIDA3YjF1VDhLNkpXb2NsREJEMlRn
        UHJVb0w0SjkyY3pJcUJjMjNQVUJIdlkKr/iu2QIdmEsQBlPGgAJEDmfdC5GXiGHk
        NqWOaDJN5OLc69RChUmpngXuzLuXRGFfL6EqhBZUIw3EjxC85OMVkg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-14T08:18:46Z"
  mac: ENC[AES256_GCM,data:cMGtzt0hY/566WYhuFF9IQaH6/Gl3rRAmpA6a59KOX7ULvnRFm8tHT7A0ZEYKuiv3IuT3J9Xk0dWqI0ghNXtDKxQ/iFtqrT45dRoEIgGCgQcXkaX9dQSxZZlmHqXnFgAD0sH64Bx+y1QKCADd9vckGCuZhdZMfAbEsokIXrsRhQ=,iv:LTz+bylPS2TIlMW0KseszJ/L1l9T1kTLhPe5In3TXxM=,tag:e2AWF5S4XXRT5MHfnDjrqw==,type:str]
  encrypted_suffix: Templates
  version: 3.12.2
