; ENC[AES256_GCM,data:+nhUCD0LBrpavF44+6PhcjOylwHC3t+Gj7IjGI9/Kwcfg2+wCaX8,iv:d1OqakWvZxFkasK00Gv0pVqDKlGxLS3+ebnqWQes2Y8=,tag:xbBQvuAmGMBPlMHsvhOw7A==,type:comment]
RUN_USER  = ENC[AES256_GCM,data:koWs,iv:oJZWueOifJz7ZbRrGps0yX8692DdlA9P+vVZA2n9AiY=,tag:WZwPIA4kXTWW8GXiOrEi9w==,type:str]
; ENC[AES256_GCM,data:wd+916ET1uSI4IHJv/Sd,iv:dmx1+mmnfEfIliaozHt6Usbo2DYQKkj+tlIftQh7msQ=,tag:cf3nCn2iA9Df2sJLgHAWWQ==,type:comment]
WORK_PATH = ENC[AES256_GCM,data:PqN04XHZ/mu3UcoPNqo=,iv:HnSUaEpwiObbMGgfX4JodAjA0bVAibrA8xdnBwRt38A=,tag:h+Rby1l8cyifmuEja/tG0Q==,type:str]

[repository]
; ENC[AES256_GCM,data:5c84DRg3lFbeSVNqES47UymACX9zvQeVOkdImmI4i0c4+r1BdK0=,iv:FsCZ6HgfCXh+SSLK+HvMRrF69FsW+b6Sofj2LVrjTu4=,tag:LmXesdPq/xhPldrolJ836A==,type:comment]
PREFERRED_LICENSES = ENC[AES256_GCM,data:qe1Q0TzVm4TFC3k=,iv:m5aRe/DrSaHXtrdndtMj6uZcM7tweVsygqYSEyhk4Hw=,tag:7moL7gRUr/M4qlUYewivsQ==,type:str]

; ENC[AES256_GCM,data:i7tZs0lePhFPjzSSPqSdnvxqffsyvMbRkvzGEq1NCkjYst1yVZj5O0G4pyz4Fz0/hE+vAUQBdMBmj0Mjju2rSkWShVLWJUW/IzFNbg5qQxW118dYRng+DBfbvp6tDsYRPwbs6TSooZ9Q7mJtzz/BSOaFZ9v6x3XlYX1zI2AnEME06Xc4ruO9CJcnHsoNKe72fxGF6CpTAzcJlQx4vUnc+7ok0USSFdMHEEaJCK5anv2Fa1ClJFO8g45pvayn/6vKWW2BO5jRwwHonjPhEzhbeVs7bCdd1h9nHTaumihK,iv:UlNWqIOfKnkETDxIq7BAiKchTPYC3N/zsOtzVlvWjsg=,tag:bQuN1lyjE1DA42vOuRcqMQ==,type:comment]
[repository.editor]

[repository.pull-request]
; ENC[AES256_GCM,data:dYhbbR69okF61n1QZ2l5CVjurGtxFKjGgC2i,iv:XBb3oCEclklc1TjeymNO+F0eDGRt+L903ctmu5vmSfs=,tag:wQRLXJlFJ92HqRR5D0UshA==,type:comment]
DEFAULT_DELETE_BRANCH_AFTER_MERGE = ENC[AES256_GCM,data:AWWFWQ==,iv:wd9HNHHW4tWXlBbW8g5qjQcDp66pQ3qZ8eWudAJ7fM8=,tag:MwBa/cU4hw+IajTYkRfYXg==,type:str]

[repository.upload]

; ENC[AES256_GCM,data:tg7wTr58tjze2UQT4AklC+QCffP1xT4D2BGFPd+S,iv:OGv/h9YBef7edB8PqX56056+vXiuQEN2WqLXwD40OV4=,tag:U+VFL4DEL4h4Xtj8U9YDxA==,type:comment]
[repository.local]

; ENC[AES256_GCM,data:TF6UvThMTeaQDZK+tsA9RG8+kCyd/l7/c3SDgb26FnipCRKM39Tk,iv:viuvaN9kJMIfeJAtzBz4xwxz0WxoClQ1Idh4x6LTzkE=,tag:UCmrzdj8PU57Gm1RJhszEA==,type:comment]
[server]
; ENC[AES256_GCM,data:fRgvsyZLuNOfMfvo0P7fDGYSVGQLGfe7JcXAWmr1,iv:lILHAOY6VW5lcVKeUdbQyoUBxLUhhHvQVvDXeZB9GHc=,tag:AclpSY6vhsxV3VzHxOLMhw==,type:comment]
DOMAIN           = ENC[AES256_GCM,data:isl+uddfo+GzsnhxIQ==,iv:nSz85FEi3c+uqV7ZHetvNpNZKnMxgTt2e0dZ/14R36g=,tag:6jVccO5bdHvgKSt8CYadeA==,type:str]
ROOT_URL         = ENC[AES256_GCM,data:xfSC8E+sapbGr4/f3YQekK6q9e59yg==,iv:OOibwDrnLarhQg28CBqx9mDD+TVJxTg8KsezYrG5yVE=,tag:Zqe8iEUgQ+j6alu/6HKDiQ==,type:str]
LOCAL_ROOT_URL   = ENC[AES256_GCM,data:8gwDc66gQW5YTn9DVv53wm0P03VFitD2iC+FvX+EtHTg,iv:7TYRBGIRvScfj9Bctyg1y6al3Cd02bAZEgwPmqAxdOc=,tag:Vw0reTh2JRszpZhvQZ6eAw==,type:str]
DISABLE_SSH      = ENC[AES256_GCM,data:SgKUqQ==,iv:C1AbTtY1JvKlisf5HxHM8SlX2VZf9q5/Qn8n5UPnvT8=,tag:GouTv1VDESgBc7OBI5tYWg==,type:str]
LFS_START_SERVER = ENC[AES256_GCM,data:DWjjgw==,iv:pY3Tbyka9yHqp0VvN9UE8PgFZrmpTXBjlyHqSfVQXCg=,tag:MOEf6MWY7rapU+IUAwC9Tw==,type:str]
LFS_JWT_SECRET   = ENC[AES256_GCM,data:Xt3ZrBvH/QhKhPySLLfjF4X2pQCjpcN3cZW4S/GXBDT/IYc4JDVm0UOG2g==,iv:roA0UJ1CFVsWZ6lcI3pnsqhiMPG82NwvdMTOuflzU6w=,tag:0wdwupivLBkES/JP/M8QHQ==,type:str]

[database]
DB_TYPE             = ENC[AES256_GCM,data:exPXlnXZ8g==,iv:CAY9GFyn6D2MLQgJHTcwD+0ddLSNpnpSQlZEuYSxEME=,tag:5Rk1c7GhqqRTjCHQG+/8jg==,type:str]
; ENC[AES256_GCM,data:pdV4ycg2qC+IK78sMO+bGTPrkyg8yaZHwvixfz786fb6IlBUyp50x9AmqGpwW/61LHv+t7DcvrX8qi7AkURLEw==,iv:h/wJGEodxS23RZERdvNHor7bCOLg8IC8m8UoOKRZvoo=,tag:fdLWCPSJCTlf9gKUiZFkiw==,type:comment]
SQLITE_JOURNAL_MODE = ENC[AES256_GCM,data:DGajn/W1,iv:VUyZxwK4lM2hYrByZTaV51nTTm6b/eoshkY8upIFvZ0=,tag:Kt2BRKrtfw4lceLTtd1RMA==,type:str]

; ENC[AES256_GCM,data:zQ4v54d4SJSmrFZBXw/8,iv:nVANfa3tB2Yd2CLED1DEEWYs+XTOfvqQLh7/4hoTL7Q=,tag:dto5RuQ+dHvzKTXwZuI9/g==,type:comment]
[security]
INSTALL_LOCK                  = ENC[AES256_GCM,data:MF/1NQ==,iv:QGV1IHEvmbAWQEuQuwd6ksea9AgrWOAtkNO/f3giA5c=,tag:wGDNdVONuZTsmEZuotojBA==,type:str]
SECRET_KEY                    = ENC[AES256_GCM,data:9uxftFKSm2vXSrFuIvK6dT8Gnv40o2NmKgzpHT5u3wBS9P4/C/N0vxUQ0tKc4XT4wMORO0k39Azj0V9EtDkqzg==,iv:6d7KNn5N10MXnbBZe65IHOGn9aR7lG7L+48uSsXc9jU=,tag:kRrgO7MSGKdCNZFLc27SjA==,type:str]
; ENC[AES256_GCM,data:1XyG7vbTFZMKJ/3JfElbjdQdUodTgPs=,iv:poJLz30buva5YxnWc4LfAw+6zyevXSo5pk45IhUZTCs=,tag:F4RUO2KA754L8eM98Mmwmg==,type:comment]
REVERSE_PROXY_TRUSTED_PROXIES = ENC[AES256_GCM,data:2A==,iv:fKazJuhZZIq6Z/rz9kAVql4Tc9BwYsLlZPkDWekxVQ0=,tag:hYxcA1Jm60FDL9PDNKcBUw==,type:str]
INTERNAL_TOKEN                = ENC[AES256_GCM,data:edgp6jI7AIyizYawEEM1Qw9Dsrg3o05AUKiNEET9/K4MZ8yopu2noS59R9DLIxzRtJlbNpcnqkAeGF6LX8CaiFaZAEwsmduAisMqZf4raClMB63PxyEBeNEaDRAbdm+wgZPHkQ7326VO,iv:AENhrBft6Cm+Lj4mlkZ4jeq+vFx026MN00Crlr49guo=,tag:wb6CtnoiEWI92DRw92QrXA==,type:str]
; ENC[AES256_GCM,data:05ped+08s6+RVo9ju7a2mJp6W3aiiMq+/Ncr,iv:cGhJ4kw6q18xHixbiofxap2IYS4I0aLQKixfNOo7xQ4=,tag:67dHu+5pmfhRZVcU9c2W9A==,type:comment]
PASSWORD_CHECK_PWN            = ENC[AES256_GCM,data:Lhw5eg==,iv:Q4gAYo3Hlko1ITS5gNoNEi3fkVf82WZkdE/AlRpJ+YI=,tag:hv0ZTWBONXA2Ui9BaQAwqA==,type:str]

; ENC[AES256_GCM,data:wpaCbBwicSIv6GfUv7hqPQg=,iv:3mcOh6X2vAJcQuZpBQX2BwH3VtAruXL+JWCz7+rakQo=,tag:Lk+sCjNaaCxYJJY9i9H4hg==,type:comment]
[openid]

; ENC[AES256_GCM,data:RqnhSQowzkfxpqenYoIRb50vq9kv3PcHt/LIzqMNDR+Kk58VPGjaIuACIbyEfs2yRzkrVjuzZvyjRP8=,iv:nxSd0Q73+D6sLrUUyl3IkrD/DpCi4RTD91iYLWnSrmo=,tag:zPffEn71gsdJWyEWP8FJDw==,type:comment]
[service]
; ENC[AES256_GCM,data:Z/RgYfjpVk+BMHR70XXFsvW/je4AKrcil+CkkhLjLiLidEwKVkLi9HAuSzfJ8Dy80UGAzozBxYQq2DKIUTKjpPngY+kNWlSIno2nPREi6l2mG+xsHPXA8Zk=,iv:gfcqBTv2zgJf6OA0rldcb2It3J96MV86CDpNUlplnvE=,tag:MdNRjOksV17rPPDCufgeDA==,type:comment]
DEFAULT_KEEP_EMAIL_PRIVATE        = ENC[AES256_GCM,data:CvPqhg==,iv:ddMk+0Qjo5GZr6lfHtmwNKTP+hX48I7a2vWDNLmv0qs=,tag:kHLd+Uj7zkFm8HQcQK5Vxg==,type:str]
DEFAULT_ALLOW_CREATE_ORGANIZATION = ENC[AES256_GCM,data:Tbm44iI=,iv:xzd9vMhI/vZUdHpcfT+ePl6shO25HHDA34XGKXn6xEc=,tag:C3k/XToUAsy/04SiqRBh4A==,type:str]
DEFAULT_ENABLE_TIMETRACKING       = ENC[AES256_GCM,data:ghcU8TE=,iv:1wisMqp4szovG40fvO3YrDga7V4wULYpICDnh3fgOes=,tag:B0t8o6wo76er6EjnqXTMIg==,type:str]
EMAIL_DOMAIN_ALLOWLIST            = ENC[AES256_GCM,data:yPdx3f2mDM/d,iv:9SuWLbLVrSoA8Qi904UK0MOnIURCh80PnHEG3XoVrZc=,tag:T0APqmtxuwn5KUwGzJ1j1A==,type:str]
ALLOW_ONLY_INTERNAL_REGISTRATION  = ENC[AES256_GCM,data:vf2zOg==,iv:Phxyae+F+Hv4AASMzoKDBqOyT/pctlZ3a1R7rSIGWuI=,tag:PBHAafuS9MAWMx+K0GV1Nw==,type:str]
NO_REPLY_ADDRESS                  = ENC[AES256_GCM,data:xIXFvsLzGwzzRFw3DY+HYj+klgUbIlM=,iv:D6KTNR+3mKBWGKRhHjNaao26FwGv4J84sVvOrxvHd70=,tag:9OZ6svdnyYiUFAja2Mt1fg==,type:str]
VALID_SITE_URL_SCHEMES            = ENC[AES256_GCM,data:1I9pAMw=,iv:Kunv06t/dbSgCzRN6htB57Gk5Apm0YJoD1gE1LazIx0=,tag:A65dSZPDtuCLDTDPKN18Sw==,type:str]

[qos]
ENABLED = ENC[AES256_GCM,data:ITEoGA==,iv:K3bs+OfPzySXf/0nRGSY1hPaSyvc6BZy/yLxrTZTi88=,tag:nllMXTEPL4unJQpmISYxWQ==,type:str]

[webhook]
ALLOWED_HOST_LIST = ENC[AES256_GCM,data:FQyH2foUnxSFIo9x0DcrKb1BL4o=,iv:k5l7/ePvsDSvT0MdiPv/xIRSaUAVNB+qB13wJIOQ4Fg=,tag:5ZvfDddOVgFx/zRVGOTt8Q==,type:str]

[session]
PROVIDER      = ENC[AES256_GCM,data:Ix9yvQ==,iv:yn+lstGkkMrwHo0EQUDrhMmAUv9XCr1Mca+SJWrcwM0=,tag:rnBz1xgT2r7VNM30eNPCUw==,type:str]
COOKIE_SECURE = ENC[AES256_GCM,data:1ezc5A==,iv:p/FXEMVOwNU8u4sZmshGG2U//YPriU3951tKa+8Ab5s=,tag:c9m7P12MpoQEQTfV3a26fA==,type:str]
DOMAIN        = ENC[AES256_GCM,data:DP7MhBJmIcO4h0714Q==,iv:03oDiYf/bcawVVSW4UJ2nXO0cxcnhdfl/63amFreaZw=,tag:MhUkCxW92rYSMfgKVlpR0Q==,type:str]
SAME_SITE     = ENC[AES256_GCM,data:vO7sea81,iv:42i1HJxWOLvQi4SnC71Uw6jjlslPyFp4SUEmrFbXgdk=,tag:biQbV2Lw8ADQ/m7fLjhZpA==,type:str]

[picture]
DISABLE_GRAVATAR           = ENC[AES256_GCM,data:tSqhBA==,iv:uJZknhBFqWmrWvMpjrcJGLsOFKOEGl5rU21Up80hblU=,tag:d0MyMkeMgjl26FQOipnoOA==,type:str]
; ENC[AES256_GCM,data:xkY35SDy7P0bT8FoC2gLCsfBca0CyDTZ6WpOWxBLMfSs64MWom8o7gxutxzc+OD2eWok9Qykb7Xe/T1HjZkb2IkEVQDbo3U3ew+ECiziVClUQqsTSwkTn6W0XUMsgBg082OmdXomh2fpUie0sATZih+okg==,iv:2Ht7gtMt1PxT2bJUybTHzQXSoqA+T2rrj0qCzHlTvaQ=,tag:47BRhc3oFn58KzezDOKX8Q==,type:comment]
REPOSITORY_AVATAR_FALLBACK = ENC[AES256_GCM,data:+9G+DuOf,iv:YPUCmkdpeU2T5tDNOZl4jWB2MeLv+v2AFU2LrDfDKZk=,tag:A9ABkItyu2XT/fxH7rKOjQ==,type:str]

[attachment]
ENABLED = ENC[AES256_GCM,data:EDOQ06M=,iv:f4z2bxGqZuTi9Mzb/chpsPDz8MAJh2G1Hg3el6K+HMI=,tag:Pwi7Dh1AcivXwGGLGy9C4A==,type:str]

[log]

; ENC[AES256_GCM,data:BI2GRl6AIGl5DtAOFP7wsXVjbxIM5jk9FRp8LXzZ8xMoPg1uJc5LM5viTEZSWhyNz5ofr0JZ/y/zXfBIYRfdCjKc1g==,iv:vyKWH0C4E6UC4MXLdOondMDKXN8MthYVNsdN687lylM=,tag:F7qfRWnQN5wnSYoHNqOj2w==,type:comment]
[cron.sync_external_users]
ENABLED = ENC[AES256_GCM,data:Vtq9Ka8=,iv:SSOVIDcRsfDeulxxMxsV5ejkbCqvS80PtqKkACk4aXk=,tag:aGDmU5AMTLafnY6f6gbnKQ==,type:str]

[cron.update_checker]
ENABLED = ENC[AES256_GCM,data:iZ6bJ7I=,iv:28YSWK5JTMwjOVHFJU3VIqbhx+VFUgUSJMQpu25s8as=,tag:4H9mzMtX4oe/jc60Ia7XIA==,type:str]

[api]
ENABLE_SWAGGER = ENC[AES256_GCM,data:lF/UCC0=,iv:Jwh+ddFmVid5DQhKcRWmX9w9coffGYpgQhWFXDc5u0c=,tag:fK97sHutIZMe9rMCYererw==,type:str]

[oauth2]
JWT_SECRET = ENC[AES256_GCM,data:LqajyyKW0kuXGv+LHQ76Q9C4j/62lvU0OmDv0o6csOZM0Lv+l4aFV2SsDw==,iv:CwNpU1oYIAeePDXpiIDgx6yQnzo67BySB2PnOz1K53c=,tag:KadD+oYLWU32+Em9yXqD/A==,type:str]

[lfs]

; ENC[AES256_GCM,data:9JrYtOtJ7GFAlkEhphhPCUNFYYFxzfG0+qZ4AHM=,iv:JJ81up4/axEbGhhnyVWFO6bXuhg/PJ6uzhTGvBoZzQ0=,tag:xB9G/8uVv8MI2nCWqHY7lg==,type:comment]
[other]
SHOW_FOOTER_VERSION            = ENC[AES256_GCM,data:QrHfcMk=,iv:15W2iXhIy5StyrD89luTr0N7PyTXpKH1Lkbqx2a71Bk=,tag:7LL/3HCzLCp5HltNaydgmg==,type:str]
SHOW_FOOTER_TEMPLATE_LOAD_TIME = ENC[AES256_GCM,data:uLNXGbw=,iv:x3HoBBJI5hmCMfGTbpO7qe8dFufWTIo0ZUJ8VPdUXbE=,tag:ehIeBhU3p2YrSkkKCpHTXw==,type:str]
SHOW_FOOTER_POWERED_BY         = ENC[AES256_GCM,data:YA4J0t8=,iv:s+JAJkOJzQ267k2CprhT6xZQcA3FB2N9nAL3hX4hUDE=,tag:A61kU+xBTHnZQR1F+bzBDA==,type:str]
ENABLE_FEED                    = ENC[AES256_GCM,data:VW8E8Q0=,iv:wML5Z3Fk7i+KfatxweqQzqjLHr7iG+8Y/+AodWSBv04=,tag:LPy679f0b1tGWx/prczhuQ==,type:str]

[sops]
age__list_0__map_recipient = age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
age__list_0__map_enc       = -----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZXFIMHd2aU92dkx3TlZr\ncWRpZjlQM09IQUx6RFlpam8yUGJVVlRLbVRZCk0zZVhmSUxiVThZdU5zcDMydnZ4\nUmU3S2FicUxTRUtwK1JKRVVrclgvNmMKLS0tIFZxSHdSVzhZbEg4YU1HblRXL0Iy\nTXlqMzVqbEgzOHBrMkI5eVNkbWd2NXMKu+lA3nN6BgLZ10lQBQtkP9l/kEj/xQku\ngzfmK+I6//mTVNwLPsAmoZzjBeG9y5j8zykitJGD4vuLAuop0sDxWw==\n-----END AGE ENCRYPTED FILE-----\n
lastmodified               = 2026-05-07T16:47:41Z
mac                        = ENC[AES256_GCM,data:1EH5MP50U/yq37oQ55tE64vohBZ7TWFyRyCML+5SP3Oktz8Yq9UPHyYsJ7peE3CvaMAaJb13LE255JYeyoPgjcDxygRVBchxaxw5stQjk9ZMJy0eNKUG852roCJX6HaomSIHpX+Rst2A2j8nL9SE8ct6I06z9r/N9X4cIikJPtA=,iv:iLKW9qhEU1WfNMgzpLjJdG1rlCh7YR7hFMrBqMo2+2k=,tag:/18KFyYKq1gl+mLL7taLmg==,type:str]
unencrypted_suffix         = _unencrypted
version                    = 3.12.2
