---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: uptrace
  namespace: flux-system
spec:
  address: https://api.uptrace.dev/v1/traces
  secretRef:
    name: uptrace
  type: otel
