---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ip-allowlist
  namespace: nullclaw
spec:
  ipAllowList:
    sourceRange:
      - ***REMOVED***
      - ***REMOVED***
      - ***REMOVED***
      - ***REMOVED***
      - ***REMOVED***
      - ***REMOVED***
      - ***REMOVED***
      - ***REMOVED***
      - ***REMOVED***
      - ***REMOVED***
