---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: infra-controllers
  interval: 1h
  patches:
    - patch: |-
        - op: replace
          path: /spec/routes/0/match
          value: Host(`traefik.${DOMAIN_NAME}`)
      target:
        kind: IngressRoute
        name: traefik-dashboard
        namespace: traefik
  path: ./infrastructure/configs
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: true
      - kind: Secret
        name: cluster-secret-vars
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  retryInterval: 2m
  timeout: 5m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 1h
  path: ./infrastructure/controllers
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
        optional: true
      - kind: Secret
        name: cluster-secret-vars
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: true
