---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/openclaw
  - resources/persistentvolume.yaml
  - resources/persistentvolumeclaim.yaml
  - resources/secret.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - claw.***REMOVED***
    target:
      kind: Certificate
      name: openclaw
      namespace: openclaw
  - patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`claw.***REMOVED***`)
    target:
      kind: IngressRoute
      name: openclaw
      namespace: openclaw
