---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/clusterrole.yaml
  - resources/clusterrolebinding.yaml
  - resources/daemonset.yaml
  - resources/deployment.yaml
  - resources/namespace.yaml
  - resources/service.yaml
  - resources/serviceaccount.yaml

configMapGenerator:
  - files:
      - relay.yaml=configs/agent-relay.yaml
    name: agent
    namespace: opentelemetry
  - files:
      - relay.yaml=configs/collector-relay.yaml
    name: collector
    namespace: opentelemetry
