---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bazarr
  namespace: media
spec:
  dnsNames: []
  duration: 168h
  issuerRef:
    kind: ClusterIssuer
    name: ownca
  privateKey:
    algorithm: ECDSA
    size: 256
  renewBefore: 8h
  secretName: bazarr-tls
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: lidarr
#   namespace: media
# spec:
#   dnsNames: []
#   duration: 168h
#   issuerRef:
#     kind: ClusterIssuer
#     name: ownca
#   privateKey:
#     algorithm: ECDSA
#     size: 256
#   renewBefore: 8h
#   secretName: lidarr-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: muxarr
  namespace: media
spec:
  dnsNames: []
  duration: 168h
  issuerRef:
    kind: ClusterIssuer
    name: ownca
  privateKey:
    algorithm: ECDSA
    size: 256
  renewBefore: 8h
  secretName: muxarr-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nzbget
  namespace: media
spec:
  dnsNames: []
  duration: 168h
  issuerRef:
    kind: ClusterIssuer
    name: ownca
  privateKey:
    algorithm: ECDSA
    size: 256
  renewBefore: 8h
  secretName: nzbget-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ombi
  namespace: media
spec:
  dnsNames: []
  duration: 168h
  issuerRef:
    kind: ClusterIssuer
    name: ownca
  privateKey:
    algorithm: ECDSA
    size: 256
  renewBefore: 8h
  secretName: ombi-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prowlarr
  namespace: media
spec:
  dnsNames: []
  duration: 168h
  issuerRef:
    kind: ClusterIssuer
    name: ownca
  privateKey:
    algorithm: ECDSA
    size: 256
  renewBefore: 8h
  secretName: prowlarr-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qbittorrent
  namespace: media
spec:
  dnsNames: []
  duration: 168h
  issuerRef:
    kind: ClusterIssuer
    name: ownca
  privateKey:
    algorithm: ECDSA
    size: 256
  renewBefore: 8h
  secretName: qbittorrent-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr
  namespace: media
spec:
  dnsNames: []
  duration: 168h
  issuerRef:
    kind: ClusterIssuer
    name: ownca
  privateKey:
    algorithm: ECDSA
    size: 256
  renewBefore: 8h
  secretName: radarr-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarr
  namespace: media
spec:
  dnsNames: []
  duration: 168h
  issuerRef:
    kind: ClusterIssuer
    name: ownca
  privateKey:
    algorithm: ECDSA
    size: 256
  renewBefore: 8h
  secretName: sonarr-tls
