---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/component: recyclarr
    app.kubernetes.io/instance: media-server
    app.kubernetes.io/name: recyclarr
  name: recyclarr
  namespace: media
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/component: recyclarr
            app.kubernetes.io/instance: media-server
            app.kubernetes.io/name: recyclarr
          name: recyclarr
          namespace: media
        spec:
          containers:
            - args:
                - sync
              envFrom:
                - secretRef:
                    name: recyclarr-env
              image: ghcr.io/recyclarr/recyclarr:8.6.0
              imagePullPolicy: IfNotPresent
              name: recyclarr
              resources: {}
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
                runAsNonRoot: true
              volumeMounts:
                - mountPath: /config
                  name: config
                - mountPath: /tmp
                  name: temp
          restartPolicy: Never
          securityContext:
            runAsGroup: 1000
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          terminationGracePeriodSeconds: 60
          volumes:
            - name: config
              secret:
                secretName: recyclarr-config
            - emptyDir: {}
              name: temp
  schedule: "@daily"
