---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: lidarr
  namespace: media
spec:
  image: ghcr.io/nosborn/lidarr
  interval: 1h
  provider: generic
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: nzbget
  namespace: media
spec:
  image: ghcr.io/nosborn/nzbget
  interval: 1h
  provider: generic
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: ombi
  namespace: media
spec:
  image: ghcr.io/nosborn/ombi
  interval: 1h
  provider: generic
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: prowlarr
  namespace: media
spec:
  image: ghcr.io/nosborn/prowlarr
  interval: 1h
  provider: generic
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: radarr
  namespace: media
spec:
  image: ghcr.io/nosborn/radarr
  interval: 1h
  provider: generic
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: recyclarr
  namespace: media
spec:
  image: ghcr.io/recyclarr/recyclarr
  interval: 1h
  provider: generic
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: sonarr
  namespace: media
spec:
  image: ghcr.io/nosborn/sonarr
  interval: 1h
  provider: generic
