# yamllint disable rule:line-length
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: media-server
  namespace: media
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        chore(media-server): update images
        {{ range .Changed.Changes }}
        - {{ .OldValue }} -> {{ .NewValue }}
        {{- end }}
  update:
    path: ./apps/base/media-server/resources
    strategy: Setters
