---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-data
  namespace: media
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: bazarr-data
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: lidarr-data
#   namespace: media
# spec:
#   accessModes:
#     - ReadWriteOncePod
#   resources:
#     requests:
#       storage: 10Gi
#   storageClassName: local-storage
#   volumeMode: Filesystem
#   volumeName: lidarr-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library # FIXME
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Ti
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: media-library
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-downloads
  namespace: media
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: nzbget-downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ombi-data
  namespace: media
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: ombi-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-data
  namespace: media
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: prowlarr-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-data
  namespace: media
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: radarr-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-data
  namespace: media
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: sonarr-data
