---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: openclaw
  name: openclaw-data
  namespace: openclaw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: openclaw-data
