apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: forgejo
  namespace: forgejo
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:rwXrOdd38w==,iv:IgKNAJkVKLNN93ZTyJ868RSAOUjIJlM4Fh8fsE2dfdE=,tag:ExULzmNgEpU3C/k7RbXQcQ==,type:str]
      stringData:
        password: ENC[AES256_GCM,data:xSXFG8eXyU46rHr4HjFTeg==,iv:xaNW35CpcdPV4WboU8tGvJfXw7tS8aKU47EQyl0E8N4=,tag:Sk3onIH2Gl8HXMF1wzVgsw==,type:str]
        username: ENC[AES256_GCM,data:8LnI/ta7FZLqKI4=,iv:3xaBqz+1nAzTXRatF0RYD7u7SCS+eyUYKFUfN5vHQFo=,tag:xemXAMttsM0z0Z4OepIJ6A==,type:str]
    - name: ENC[AES256_GCM,data:nhn+ke7lNHJ8pfmRJA==,iv:FU6nWraziwekY1kNjcgtNx479KUJP6XaUoJ2b6c8ufE=,tag:tTWjvpDv+7eaWBwCKgJpfQ==,type:str]
      stringData:
        password: ENC[AES256_GCM,data:xSXFG8eXyU46rHr4HjFTeg==,iv:xaNW35CpcdPV4WboU8tGvJfXw7tS8aKU47EQyl0E8N4=,tag:Sk3onIH2Gl8HXMF1wzVgsw==,type:str]
        username: ENC[AES256_GCM,data:8LnI/ta7FZLqKI4=,iv:3xaBqz+1nAzTXRatF0RYD7u7SCS+eyUYKFUfN5vHQFo=,tag:xemXAMttsM0z0Z4OepIJ6A==,type:str]
    - name: ENC[AES256_GCM,data:XkHi8xPyToBDgHmIipZc/fxGCLAM,iv:wDegrFVIZEv5NFj0yjkRn0vh6pYzls3sVCNoUqm/c6Q=,tag:WE6WsA6wyS5qqrF8QP7elA==,type:str]
      stringData:
        _generals_: ENC[AES256_GCM,data:BLQ7LPR8z4ITWDhQAyQIlBgftWcMwwVJcLymuRleJ44g5tGpYXknvjwLvNMHpM4quHK5gYAWSUo=,iv:EiWb0Z2Gcb1Y5MUPihs6QgSDFVGMUg3UntEgAbDosBw=,tag:AGfrk943VlY3MS6PRnFwkg==,type:str]
        cache: ENC[AES256_GCM,data:SwqATb0T8HagmOU99KQKa6yymqI=,iv:bhrNxwyhj0FZYbnDZMEtUt7GxS0sUnzDRpMcxUSU6+E=,tag:L0k51y7+0rCfYD9Nlc96RQ==,type:str]
        database: ENC[AES256_GCM,data:/p/PB9dLiYZPOKwf49JF,iv:zvpm+2NWN8Y70qm0ZbPIWXfCRGj9J4qW6WbRK6KQRAQ=,tag:HipBgy1HIFuR4Uu0nfRKWA==,type:str]
        metrics: ENC[AES256_GCM,data:DnWFp0bT5PCq48yKwg==,iv:Y8T58BiZu9q14y/2slTsUD6fzV1JB3HRAKeJ1S9nHrs=,tag:qIrZJ+dfGuE4I+luK1jlHQ==,type:str]
        queue: ENC[AES256_GCM,data:iFHCcnpawQSXtrz8DZgP/kcpcs4=,iv:UhL9EK/YnwtcgVV0dsurbs5QxG6QQB/lc5Pm8NQTucQ=,tag:L+Boat5y5RpJ6ez6KoVEAA==,type:str]
        repository: ENC[AES256_GCM,data:gdnlv0WHDc2z7jDgYKJCbiN5yU/Mjfj/n7LOKZqAaEnk,iv:EwJz5iJ8xk/xfYqAqslBbnXaQCRHbQaFe8/1/AVOWOM=,tag:1zS7vO7VQaW/nRNUZ3bqLA==,type:str]
        security: ENC[AES256_GCM,data:2VYMNP29SNKDUp35F6OR3DA=,iv:emXpA7t3ut48Q8VpYSXk0OS55cZumD8yZtFekJVbp/c=,tag:2z691yxans8JxQ1F3/hfxA==,type:str]
        server: ENC[AES256_GCM,data:NjuOYwMHJi+jpHQkwitcWCp/8BZDGnI7BLmOnKMlff5HQDL2mbdX25Ew/tx8jNXgeIuOHszRD7Ccu3kVJTom/VY0IuncWGMzgK8aZPFjLeJe+Q7n+FrRGKdjXN+RDdgZbWtIeFLEYYcyshZRqFEsOS9VpJH8tULWKgmcycWH28viCj1YelVqWqCtspc3zo9GZvxdbnr12yExTN5Zs0KSm7IfSPrxMGqowJlVtl0e+QbiiEBOZe++/ZnOYTNKmjWlKCXJnEi+,iv:MYECCrxUf5agR5bgCUXr7KLe1+XNtZ1rllzlrpY0rdU=,tag:KuFhtt9bsaN4XZP9JupqRw==,type:str]
        session: ENC[AES256_GCM,data:0zmB/fouU6WlfvYBblUtsuUBmozMH15uiTBPc2jfjdA=,iv:cqnf5jBZ+orUbTu69gDHYnv+f+9Gj05IUcEHkeBE8oQ=,tag:p2zaZ6+i4XsRvCRVICD9TA==,type:str]
sops:
  age:
    - recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RFFsK2xlMUlDTklPUmVM
        RnJaaXZLTjh3VWZvVXhadFF4SXBOczNrV0M4Cmk3eVZDUStjb2JWM1gzaFFBeGFF
        clBpZU8xVTFrOVhnQTY4VCtDM3hkaTQKLS0tIDA3YjF1VDhLNkpXb2NsREJEMlRn
        UHJVb0w0SjkyY3pJcUJjMjNQVUJIdlkKr/iu2QIdmEsQBlPGgAJEDmfdC5GXiGHk
        NqWOaDJN5OLc69RChUmpngXuzLuXRGFfL6EqhBZUIw3EjxC85OMVkg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T20:06:11Z"
  mac: ENC[AES256_GCM,data:4YKO8//wy53sutHhRMBqMynXGfO13+4nfmvK6sMY9+qNc5riF8VRCxqStzFghcWBTatd4noFSPmGnr/aQx9sCy5Xscjr9O+2JgFASEUsKYh823hwklTdC3DkGXPgczwUXovOUg99p0gfISDD6QCjIJESgvwXJmbYCPsX5T8QE24=,iv:s75Jyjo8qR613trmbFdU5PPRf2YUSimwAwFUWyhIj1M=,tag:rWqX8m2w7RJkFMzomMsaYg==,type:str]
  encrypted_suffix: Templates
  version: 3.12.2
