apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: forgejo-admin
  namespace: forgejo
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:QRJTRpfPxpp5Y8QCsp+Fs5s4vw==,iv:x69gcvnYfNTh3dVC2YqL71RBuukyYo8yJmDyS4/Rsfc=,tag:Q8vkvP7py9s7e0afb1dAOQ==,type:str]
      stringData:
        GITEA__OAUTH2__JWT_SECRET: ENC[AES256_GCM,data:J3bP+vazH1eWBSBUg/ysk4bW2flPVoUduS7OuzC6zX1aNPgw8zN+nfZDUg==,iv:RA2HYdhueroB8WBVeg4KLntWPTNuKK4OHErJGz9DjF0=,tag:ozb9ZAb2juI3cODeeJi1Yw==,type:str]
        GITEA__SECURITY__INTERNAL_TOKEN: ENC[AES256_GCM,data:0ciiC4ht0HvtTOUPP9xK8oOi0bqNEb2PC+J1K0XHU4l/m2nk0bwTxQdVaomyArZA20jcP8jexq84IJQUis9BoSXVk8j2+2wevWa1jzBetCqnYvbyMIOTe9AOB2xOTF/7m1de/rtZZuqV,iv:CqLyo3bvZvRilVbWcWo5t6ItA1/19B3wJGkiHdr8JjY=,tag:O4uJe59FcI5reww46zzmug==,type:str]
        GITEA__SECURITY__SECRET_KEY: ENC[AES256_GCM,data:LegHF8HwPQii52DuAbvNpd2bf6m0egfYfnxUT1BKbO35PqZHepKo1mfCPCgA7+5oBJugSjvR8y+mf6i61teGIQ==,iv:hN0ZceR/TcmVrXVek094ZmR2vbxhvRrYCou1wKhMKpY=,tag:341LGCfdNZPG30xeRWFI7g==,type:str]
        GITEA__SERVER__LFS_JWT_SECRET: ENC[AES256_GCM,data:aYmWCoIS9Cla/XbvuzrpZeGdLE9LD51e1qCNjSUucEB/IeS+yPcRBlXQmg==,iv:S4BphYmjmli5qhkzYBLHmESyj/SE5x9JOiwcn8tPf4U=,tag:6RRmv52Eu5p0O322emVMqA==,type:str]
    - name: ENC[AES256_GCM,data:ARR25HAJdSkYlp8U43BVcHP1,iv:6SxoRo4w3DwQFmDUN/dXMtHRf85v6GgFDyWkrM6J7EQ=,tag:aAkzlnfHdVbTY10hyF7X6w==,type:str]
      stringData:
        GITEA_ADMIN_PASSWORD: ENC[AES256_GCM,data:9u/BtdUJMZYDa8J/ro889Q==,iv:O7iaLjtKs1WeyTI16sAqQN2Jh4EUhnNopMfwTY4B7eU=,tag:4n1k0+qFfYhIjlp5Aj459A==,type:str]
        GITEA_ADMIN_USERNAME: ENC[AES256_GCM,data:h25MfbTNq49HzrtksA==,iv:dE+hhb+KMDSuTp+8O1F5ba7GdyKXIqSx5LyhwLTVTvI=,tag:ZpBKjBWTD3IkwEg3GIjdNg==,type:str]
sops:
  age:
    - recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RFFsK2xlMUlDTklPUmVM
        RnJaaXZLTjh3VWZvVXhadFF4SXBOczNrV0M4Cmk3eVZDUStjb2JWM1gzaFFBeGFF
        clBpZU8xVTFrOVhnQTY4VCtDM3hkaTQKLS0tIDA3YjF1VDhLNkpXb2NsREJEMlRn
        UHJVb0w0SjkyY3pJcUJjMjNQVUJIdlkKr/iu2QIdmEsQBlPGgAJEDmfdC5GXiGHk
        NqWOaDJN5OLc69RChUmpngXuzLuXRGFfL6EqhBZUIw3EjxC85OMVkg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T15:55:19Z"
  mac: ENC[AES256_GCM,data:NM1AplC09yfVtbFBJaT+J0kytHwezSzPXoRAVuBR7wgo2FQG9KPTuQVpzA0zMv+8TsS0WLz41vFZkxa2S55wVyQommKaXA53NI9bYnJ5pK6+XqBVpyk03idbXlA48IrXtrrk7wg21QyPR9vYnRmI6n5+SyCFuZyp87m7XMpx9E4=,iv:ClTMyky+rFwA9I34zuiQavqLQAseBIdz2DU43coJeeA=,tag:G4nxOt0TZpznUBSdh2P+oQ==,type:str]
  encrypted_suffix: Templates
  version: 3.12.2
