---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  labels:
    app.kubernetes.io/instance: zeroclaw
    app.kubernetes.io/name: zeroclaw
  name: zeroclaw
  namespace: zeroclaw
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`claw.example.com`)
      middlewares:
        - name: ip-allowlist
        - name: security-headers
      services:
        - name: zeroclaw
          port: 80
  tls:
    secretName: zeroclaw-tls
