---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app.kubernetes.io/instance: zeroclaw
    app.kubernetes.io/name: zeroclaw-data
  name: zeroclaw-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    name: zeroclaw-data
    namespace: zeroclaw
  iscsi:
    fsType: btrfs
    iqn: ***REMOVED***
    lun: 5
    targetPortal: ***REMOVED***
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
