---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: zeroclaw
    app.kubernetes.io/name: zeroclaw-data
  name: zeroclaw-data
  namespace: zeroclaw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: zeroclaw-data
