---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: zeroclaw
    app.kubernetes.io/instance: zeroclaw
    app.kubernetes.io/name: zeroclaw
  name: zeroclaw
  namespace: zeroclaw
