---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/certificate.yaml
  - resources/deployment.yaml
  - resources/httproute.yaml
  - resources/middleware.yaml
  - resources/namespace.yaml
  - resources/networkpolicy.yaml
  - resources/secret.yaml
  - resources/service.yaml

configMapGenerator:
  - files:
      - scripts/fetch-content.sh
    name: miasma-nginx-scripts
    namespace: miasma

secretGenerator:
  - files:
      - configs/nginx.conf
    name: miasma-nginx
    namespace: miasma
