---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app.kubernetes.io/instance: pocket-id
    app.kubernetes.io/name: pocket-id-data
  name: pocket-id-data
spec:
  accessModes:
    - ReadWriteOncePod
  capacity:
    storage: 1Gi
  claimRef:
    name: pocket-id-data
    namespace: pocket-id
  iscsi:
    fsType: btrfs
    iqn: ${ISCSI_IQN}
    lun: 4
    targetPortal: ${ISCSI_TARGET_PORTAL}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
