---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/certificate.yaml
  - resources/cronjob.yaml
  - resources/deployment.yaml
  - resources/ingressroute.yaml
  - resources/middleware.yaml
  - resources/namespace.yaml
  - resources/networkpolicy.yaml
  - resources/role.yaml
  - resources/rolebinding.yaml
  - resources/service.yaml
  - resources/serviceaccount.yaml

configMapGenerator:
  - files:
      - configs/config.toml
    name: zeroclaw-config
    namespace: zeroclaw
    options:
      labels:
        app.kubernetes.io/component: zeroclaw
        app.kubernetes.io/instance: zeroclaw
        app.kubernetes.io/name: zeroclaw
