---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/immich
  - sopssecret.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - photos.***REMOVED***
    target:
      kind: Certificate
      name: immich
      namespace: immich
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            cpu: !!str 1
            memory: 2Gi
    target:
      kind: Deployment
      name: immich-machine-learning
      namespace: immich
