apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: immich
  namespace: immich
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:25rc0XjI/ah5F0IOH7nD,iv:uJlayfG3wuwWIq74qqq6cBO8MtRL7wI+ddKqJATnF4c=,tag:yRYko3pJgqKHRe+COKSn+g==,type:str]
      stringData:
        postgres-password: ENC[AES256_GCM,data:YY7e2YAYlxRsedEpjyh6ow==,iv:iPm+7+q2gsw5mCKG2MWz4A+x1LC9yZYu720oJZqLGVo=,tag:RLooKV+nmu+LiPeEtEHK1w==,type:str]
sops:
  age:
    - recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RFFsK2xlMUlDTklPUmVM
        RnJaaXZLTjh3VWZvVXhadFF4SXBOczNrV0M4Cmk3eVZDUStjb2JWM1gzaFFBeGFF
        clBpZU8xVTFrOVhnQTY4VCtDM3hkaTQKLS0tIDA3YjF1VDhLNkpXb2NsREJEMlRn
        UHJVb0w0SjkyY3pJcUJjMjNQVUJIdlkKr/iu2QIdmEsQBlPGgAJEDmfdC5GXiGHk
        NqWOaDJN5OLc69RChUmpngXuzLuXRGFfL6EqhBZUIw3EjxC85OMVkg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-14T08:15:36Z"
  mac: ENC[AES256_GCM,data:jzp6dGqYoYakbLyXUR/jOqY+u4wzwmZiQQ1JwwE3Oc9yNJ7LcqrhvV/D16J8YOUF2Jy4fbuxQALzKgn0DkXOpeDAu4ivBuJz/O7YqtLXDu3tp558oX6y7yrnD3SwC38n8pTMzSHvEJn67WFTGhoEz7iK8iT0REgp2NVhtNTC1cc=,iv:nmCU8t7nRP1amclgbQEc7fMwMyN/xwjXVkPL+3PLkpU=,tag:gU8dHqG3VXFvZPf/0ptDBg==,type:str]
  encrypted_suffix: Templates
  version: 3.12.2
