---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tt-rss
  namespace: rss
spec:
  dnsNames:
    - rss.example.com
  duration: 168h
  issuerRef:
    kind: ClusterIssuer
    name: ownca
  renewBefore: 8h
  secretName: tt-rss-tls
