---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gotk-alert.yaml
  - gotk-components.yaml
  - gotk-provider.yaml
  - gotk-receiver.yaml
  - gotk-sync.yaml

patches:
  - patch: |
      - op: add
        path: /spec/revisionHistoryLimit
        value: 0
    target:
      kind: Deployment
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 4m
            memory: 34Mi
    target:
      kind: Deployment
      name: helm-controller
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 5m
            memory: 61Mi
    target:
      kind: Deployment
      name: kustomize-controller
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 6m
            memory: 33Mi
    target:
      kind: Deployment
      name: notification-controller
  - patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 2m
            memory: 36Mi
    target:
      kind: Deployment
      name: source-controller
