---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/mitmproxy

secretGenerator:
  - files:
      - configs/config.yaml
      - configs/mitmproxy-ca.pem
      - configs/mitmproxy-dhparam.pem
    name: mitmproxy-config
    namespace: mitmproxy

patches:
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - auth.ngp-discovery.co.uk
    target:
      kind: Certificate
      name: mitmproxy
      namespace: mitmproxy
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - mitmproxy.${DOMAIN_NAME}
    target:
      kind: Certificate
      name: mitmweb
      namespace: mitmproxy
  - patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`auth.ngp-discovery.co.uk`)
    target:
      kind: IngressRoute
      name: mitmproxy
      namespace: mitmproxy
  - patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`mitmproxy.${DOMAIN_NAME}`)
    target:
      kind: IngressRoute
      name: mitmweb
      namespace: mitmproxy
