---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/deployment.yaml
  - resources/imagepolicy.yaml
  - resources/imagerepository.yaml
  - resources/imageupdateautomation.yaml
  - resources/ingressroute.yaml
  - resources/middleware.yaml
  - resources/namespace.yaml
  - resources/networkpolicy.yaml
  - resources/persistentvolume.yaml
  - resources/persistentvolumeclaim.yaml
  - resources/role.yaml
  - resources/rolebinding.yaml
  - resources/service.yaml

configMapGenerator:
  - envs:
      - configs/pds.env
    name: pds-env
    namespace: pds
