apiVersion: v1
kind: Secret
metadata:
  labels:
    reconcile.fluxcd.io/watch: Enabled
  name: uptrace
  namespace: opentelemetry
stringData:
  dsn: ENC[AES256_GCM,data:OOv1DgvJ9AhKwSZZV/x+AJX1KRdRKRmgfbnJHvAVxnzwk31UgdMrnHZoYd/kiJkG1xQuEtQghGY=,iv:JRj/IIRzXSyRCXf+VH13p8vo9nCF29vozkIhLuBU0+U=,tag:bqI2ofLwdKepb94DqMWOsQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLam1jQVBSN2pnRytDSWNX
        WGk1ajBRbUpOMktXMTZNTnIva25MSnpBWUJBCmZ6RWtmaFQvaWdkbWNvMTRBZ211
        U0p3dlpQK3BRakVGclB3ZFozaUR4eWMKLS0tIFQ3S2JJTU1nTHB5R213c2JLUXU3
        TXFKSXdKNWlrV2pZdUlicGlIa2tlL00KZohAY3NFGK2dl23skpcRJp72WC3od66Y
        58pm0+MaG06V6Q2ZJXyAj17VSIy6IgWBpQy+g4EpnHzVmkIg/5yYJg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-11T07:42:14Z"
  mac: ENC[AES256_GCM,data:vQGRkGYh2APp0Rtj6VSrr0v2t8LRUQIO/7LCg/sp0da/xGOxr+ticQIzM7t5oOTkE9kkA1HPalgZUi2ipZrnyZX4JTcQCRWYXjHmLdImAnw7F9R+u7m5GoJkuauK1k6W9ltZJWRwOW2O7HG5BavkEPTc9SHP7S+limccUljZwkA=,iv:+2/XxcXzZG9xwqdR8Admfhffnx/AP+pxmADKPbpmTsA=,tag:hDGvjpkrVDfxNuEEG4mxCg==,type:str]
  version: 3.13.0
