---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    secret.reloader.stakater.com/reload: freshrss-config
  labels:
    app.kubernetes.io/instance: freshrss
    app.kubernetes.io/name: freshrss
  name: freshrss
  namespace: freshrss
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: freshrss
      app.kubernetes.io/name: freshrss
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: freshrss
      labels:
        app.kubernetes.io/instance: freshrss
        app.kubernetes.io/name: freshrss
    spec:
      containers:
        - env:
            - name: CRON_MIN
              value: 1,31
            - name: TZ
              value: Europe/London
          image: ghcr.io/nosborn/freshrss:1.28.1
          imagePullPolicy: Always
          # livenessProbe:
          #   failureThreshold: 10
          #   httpGet:
          #     path: /api/healthz
          #     port: http
          #   initialDelaySeconds: 200
          #   periodSeconds: 10
          #   successThreshold: 1
          #   timeoutSeconds: 1
          name: freshrss
          ports:
            - containerPort: 80
              name: http
          # readinessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /api/healthz
          #     port: http
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          #   successThreshold: 1
          #   timeoutSeconds: 1
          resources: {}
          # securityContext:
          #   allowPrivilegeEscalation: false
          #   capabilities:
          #     drop:
          #       - ALL
          #   readOnlyRootFilesystem: true
          #   runAsNonRoot: true
          volumeMounts:
            - mountPath: /var/www/FreshRSS/data
              name: data
      securityContext:
        fsGroup: 33
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 60
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: freshrss-data
