---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: freshrss-data
  namespace: freshrss
spec:
  accessModes:
    - ReadWriteOncePod
  capacity:
    storage: 10Gi
  hostPath:
    path: /srv/freshrss
    type: Directory
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
