---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/gitea
  - resources/persistentvolume.yaml
  - resources/persistentvolumeclaim.yaml
  - resources/secret.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - git.osborn.io
    target:
      kind: Certificate
      name: gitea
      namespace: gitea
  - patch: |-
      - op: add
        path: /spec/template/spec/initContainers/0/env/-
        value:
          name: COOKIE_DOMAIN
          value: git.osborn.io
      # - op: add
      #   path: /spec/template/spec/initContainers/0/env/-
      #   value:
      #     name: PUBLIC_URL
      #     value: https://git.osborn.io
      - op: add
        path: /spec/template/spec/initContainers/0/env/-
        value:
          name: REDIRECT_DOMAINS
          value: git.osborn.io
    target:
      kind: Deployment
      name: gitea
      namespace: gitea
  - patch: |-
      - op: replace
        path: /spec/hostnames
        value:
          - git.osborn.io
    target:
      kind: HTTPRoute
      name: gitea
      namespace: gitea
  - patch: |-
      - op: add
        path: /spec/egress
        value:
          - to:
              - ipBlock:
                  cidr: 10.42.0.0/16
              - ipBlock:
                  cidr: 10.43.0.0/16
              - ipBlock:
                  cidr: fd42::/56
              - ipBlock:
                  cidr: fd43::/112
          - to:
              - ipBlock:
                  cidr: 0.0.0.0/0
                  except:
                    - 10.0.0.0/8
                    - 169.254.0.0/16
                    - 172.16.0.0/12
                    - 192.168.0.0/16
              - ipBlock:
                  cidr: ::/0
                  except:
                    - ${IPV6_DELEGATED_PREFIX}
                    - fc00::/7
                    - fe80::/10
      - op: add
        path: /spec/policyTypes/-
        value: Egress
    target:
      kind: NetworkPolicy
      name: gitea
      namespace: gitea
