---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/gitea
  - resources/persistentvolume.yaml
  - resources/persistentvolumeclaim.yaml
  - resources/secret.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/initContainers/0/env/-
        value:
          name: COOKIE_DOMAIN
          value: osborn.io
      - op: add
        path: /spec/template/spec/initContainers/0/env/-
        value:
          name: PUBLIC_URL
          value: https://git.osborn.io
    target:
      kind: Deployment
      name: gitea
      namespace: gitea
  - patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`git.osborn.io`)
    target:
      kind: IngressRoute
      name: gitea
      namespace: gitea
