apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: searxng
  namespace: searxng
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:P3f5zfQPRSGGuco=,iv:4Xg4fhqcO5pygsSrYvANVoSXNacsekj1mC4f8tMN1D0=,tag:iUp6XTJGAbJh0qT40y1jBw==,type:str]
      stringData:
        SEARXNG_SECRET: ENC[AES256_GCM,data:d7Yo2IBv+xSVoqK7ju6XCTOktB2FRb7d28cMzAepU8M=,iv:HNuaFKL3dN/2S1/2OXMTdvFPYZhEghtHsYK2xQqteUI=,tag:orm7GAw2PhvxFNexY94QDQ==,type:str]
sops:
  age:
    - recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RFFsK2xlMUlDTklPUmVM
        RnJaaXZLTjh3VWZvVXhadFF4SXBOczNrV0M4Cmk3eVZDUStjb2JWM1gzaFFBeGFF
        clBpZU8xVTFrOVhnQTY4VCtDM3hkaTQKLS0tIDA3YjF1VDhLNkpXb2NsREJEMlRn
        UHJVb0w0SjkyY3pJcUJjMjNQVUJIdlkKr/iu2QIdmEsQBlPGgAJEDmfdC5GXiGHk
        NqWOaDJN5OLc69RChUmpngXuzLuXRGFfL6EqhBZUIw3EjxC85OMVkg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-14T08:23:18Z"
  mac: ENC[AES256_GCM,data:8+c1SCUdZara3mfBoM5FzJwCdV1gTRF2Ay5YDL1RxPTU9QbyuKlDqrjFU+5QMtS3MrEESTEVydcLlPDVQ/GrtzaF9KX7d1GUCC/Vgo8HacePBLJUB1V6qcB4G0uEEivNpUoIDMQa6eqK5pTZuAldAyUCHDMfjL9a2aOGEi+W9E0=,iv:WB6HPsrO8OXOMyp1pkTxgiIfDsW4m2YeW7D9mpSXB7Y=,tag:lOHK9J+3vuB/a4WOxxb8tw==,type:str]
  encrypted_suffix: Templates
  version: 3.12.2
