---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager.yaml
  - nvidia-device-plugin.yaml
  - opentelemetry
  - reloader.yaml
  - sops-secrets-operator.yaml
  - traefik.yaml
