# yamllint disable rule:line-length
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 1h
  url: https://traefik.github.io/charts/
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/enforce: restricted
  name: traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 41.0.2
  install:
    remediation:
      retries: 3
  interval: 1h
  maxHistory: 1
  postRenderers:
    - kustomize:
        patches:
          - patch: |-
              - op: replace
                path: /spec/routes/0/match
                value: Host(`traefik.${DOMAIN_NAME}`)
            target:
              kind: IngressRoute
              name: traefik-dashboard
  upgrade:
    crds: CreateReplace
  values:
    accessLog:
      dualOutput: true
      enabled: true
      fields:
        names:
          RequestHost: keep
      otlp:
        enabled: true
        grpc:
          enabled: true
          endpoint: collector.opentelemetry.svc:4317
          insecure: true
    deployment:
      revisionHistoryLimit: 0
    experimental:
      otlpLogs: true
    global:
      checkNewVersion: false
      sendAnonymousUsage: false
    ingressRoute:
      dashboard:
        enabled: true
        entryPoints:
          - websecure
        middlewares:
          - name: ip-allowlist
            namespace: traefik
          - name: security-headers
            namespace: traefik
        tls:
          secretName: traefik-dashboard-tls
    metrics:
      otlp:
        enabled: true
        grpc:
          enabled: true
          endpoint: collector.opentelemetry.svc:4317
          insecure: true
    ports:
      traefik:
        expose:
          default: true
      websecure:
        allowACMEByPass: false # TODO: true?
        http:
          encodedCharacters:
            allowEncodedBackSlash: false
            allowEncodedHash: false
            allowEncodedNullCharacter: false
            allowEncodedPercent: false
            allowEncodedQuestionMark: false
            allowEncodedSemicolon: false
            allowEncodedSlash: false
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
      kubernetesGateway:
        enabled: true
      kubernetesIngress:
        enabled: false
    service:
      spec:
        externalTrafficPolicy: Local
    tracing:
      otlp:
        enabled: true
        grpc:
          enabled: true
          endpoint: collector.opentelemetry.svc:4317
          insecure: true
    updateStrategy:
      type: Recreate
