---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 1h
  url: https://traefik.github.io/charts/
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/enforce: restricted
  name: traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 41.0.2
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
  interval: 1h
  maxHistory: 1
  upgrade:
    crds: CreateReplace
  values:
    accessLog:
      dualOutput: true
      enabled: true
      fields:
        names:
          RequestHost: keep
      otlp:
        enabled: true
        grpc:
          enabled: true
          endpoint: collector.opentelemetry.svc:4317
          insecure: true
    deployment:
      revisionHistoryLimit: 0
    experimental:
      otlpLogs: true
    global:
      checkNewVersion: false
      sendAnonymousUsage: false
    ingressRoute:
      dashboard:
        enabled: false
    metrics:
      otlp:
        enabled: true
        grpc:
          enabled: true
          endpoint: collector.opentelemetry.svc:4317
          insecure: true
    ports:
      traefik:
        expose:
          default: true
      web:
        allowACMEByPass: true
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
      websecure:
        allowACMEByPass: true
        http:
          encodedCharacters:
            allowEncodedBackSlash: false
            allowEncodedHash: false
            allowEncodedNullCharacter: false
            allowEncodedPercent: false
            allowEncodedQuestionMark: false
            allowEncodedSemicolon: false
            allowEncodedSlash: false
    providers:
      kubernetesGateway:
        enabled: true
      kubernetesIngress:
        enabled: true
    service:
      spec:
        externalTrafficPolicy: Local
    tracing:
      otlp:
        enabled: true
        grpc:
          enabled: true
          endpoint: collector.opentelemetry.svc:4317
          insecure: true
    updateStrategy:
      type: Recreate
