apiVersion: v1
kind: Secret
metadata:
  labels:
    reconcile.fluxcd.io/watch: Enabled
  name: recyclarr-env
  namespace: media
stringData:
  RADARR_API_KEY: ENC[AES256_GCM,data:Ib2gnwD2Df1nbSfSzvQbIm4lCW/O3FrHYGIckFmzrVI=,iv:KGJHKOu802HCfRFqEDvg/OyjmjgVUSs8vPIv3SflsTo=,tag:h6mjLW3jtvW5tz1hUOoDBA==,type:str]
  SONARR_API_KEY: ENC[AES256_GCM,data:3Ch4Y596ElbrScu4H1zghg98DsRy/a+22VNfVojCmio=,iv:pB3ZLZ0szHZ5a0bT1OSkioVIy9Nwd+n0Z/SF/8xkKtI=,tag:s1LfeB2k16dbx54pQ5Mm6g==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM09IdnJEejNkQkZ3Yzh5
        SW05M1dQak5PRWN0eENIOGU3cEVBZ3VYNXhZCnIxV3FlcE9TdGZCdmlUWHJIK0p3
        bmtQWWhJVm9kM1o0NXM2dFlSS2xiME0KLS0tIHhDTlhEVFJuWXFSa0Jkd3h4Y2JP
        SzBDcTV5U0pzSFRxbTNCVElHVm1BVEkKdLFk1SONr7goJVo9XiyeNw4hFTZZIuQa
        bMCii8Umb4D48Ov7Yiv2y5yx7LZU7joYqdsvR8FvDvR8ks/MKyIoMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-11T17:08:59Z"
  mac: ENC[AES256_GCM,data:bskqud0l6FVBnqVfwdaXXOPFh3eqkIK8xULm0JsyvncsgBj3Raj4FDQLeV0DFF5GZcOsphmFr9cYit+GqSVgUIVGy0Ig+QQUn/8GL38f1Ghdey7jiB4DbXVCZDj3w3PzWJSje84YYzkWWKRI9JaKnQb/UOhubgjtrlVNzvIWJgo=,iv:qM+sAUzzxe2kb0inmKENN35+wYOs7tewOEWDmZ3zglY=,tag:QRt4D1Gpe53+l98piUBrUg==,type:str]
  version: 3.13.0
