apiVersion: v1
kind: Secret
metadata:
  labels:
    reconcile.fluxcd.io/watch: Enabled
  name: lidarr-config
  namespace: media
stringData:
  config.xml: ENC[AES256_GCM,data:LcaA6R0mqEXMzFoddt3JoYmrWGupiuPnRQgVbUSrGPugerQO8DrWptoTypuYL9tvtDCRMXdQn1wqY3ltLU2JbQLKLZF0celAxViPPbJsDuO8lyFpenq1g4/eW5Q5hfnLaeSvUyWDdYjtRpAL0uHK+XeizPl9XYPHP0pKICZsthBByd0sjIM+P4dC7wPRvZDm9iyL0+AYKv3GBQE0qYk+VXR/kYIJgH2YM3URXzPeQNj1rRDn/I0/pD0NO5QiCOnqyfA+M/iB4N6r3qPt42zjMfxdtO1bfgO0CtqgZBiEe5Wm6YU6MUXsn6FuumpEwATfmzok0TKS2wNoXROZd2ftoBhUruNJIpq2CI/IuRjm9LP1Hsg4zL8/Ne+ACZF9lwxEMzwt47o6sNtXz9C8yqVEPjuSoNdqizxZE8Oo3KMzuIMvxBHKknzg6rRn83aYErQhARNZO9QPoODHPHOOEU4/fw1PleBfSYcDWHOPxHTGmCXVuXq0yOcfzu4Q/vHQEJkIiJCk3bcNCruea617PL2EL7QkHn8Wr6WcZMta26EfnU37ApHn3Ry4c6bSxnXWK9yC8LnfEO3BB7gloXADxiQhcJeVtYXK1jLKWOiiZ1er81fZSMbXqlwumK66ASo48S1R4uMIuqvEqyrAcAr9JbyuyeyW4+0hbqAmrdTQzgjFAhPjK8h8VJb+8Teg6crpunkhIWeZUNvLZMjcqqHxun4oukCSep05JqcTxQ0UChWUPsbHFQnvBptoPNaRT8pm81Nsb7yz4mrwc2tmPry6xiZ+2tmSMNum,iv:CWE8i9neH25TxbrdAhbFFBlzTKgzcO7u7U3Ko670xWc=,tag:nZgJafDDXfSwACjl5wfzIQ==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM09IdnJEejNkQkZ3Yzh5
        SW05M1dQak5PRWN0eENIOGU3cEVBZ3VYNXhZCnIxV3FlcE9TdGZCdmlUWHJIK0p3
        bmtQWWhJVm9kM1o0NXM2dFlSS2xiME0KLS0tIHhDTlhEVFJuWXFSa0Jkd3h4Y2JP
        SzBDcTV5U0pzSFRxbTNCVElHVm1BVEkKdLFk1SONr7goJVo9XiyeNw4hFTZZIuQa
        bMCii8Umb4D48Ov7Yiv2y5yx7LZU7joYqdsvR8FvDvR8ks/MKyIoMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-12T13:28:26Z"
  mac: ENC[AES256_GCM,data:Rfj3rkItxjYByMn9n16I8K7F3b0PQQC1M4UymNoIbgXzAH+4W6/6DCuIKfX6liRDabE83R5CUNbRZkNZO4ZtDGdE4M4hgk1RW8jqklZ96qbXoUcqVUqZcd7vDNrAtgZOLztJvuez1eCz3H51eEFwIcRUS7ByKJZNsdJJb2SCwpc=,iv:9hgp3nuA65sUcn9/msF+jS9raT6M1aio88X1WIMbIws=,tag:/XniugnLlCgZQ1FZEByVhg==,type:str]
  version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    reconcile.fluxcd.io/watch: Enabled
  name: nzbget-config
  namespace: media
stringData:
  nzbget.conf: ENC[AES256_GCM,data:GNBxdWuK0HRhvQDT6iZoag2DGvctgW253LxWGWK4FHuQbUcx2Fb/S1vgdXLAi5snjFCixJf+Xmdqz53bQy+X5044RN1EOGH/QK2Z8lLkYc7Y4KQfnTxITl+p2Z+pkwOnMrrqpKSEJe358JL48H+uQFcoPvOejh/ksNRWW6G3liS1E12Y3VX/zEcG1IwsmS+5o1Kq+RYTY0sYPIX05Ozev8a3BxM6b01tX/d5VKRHK/PTkUfGSFv7LIJ0Mq/pIUTPrV7Q55SMYUeOx4GuiZljlnp8ifCrRlBlgrmU6oKF8C+kFFEUEgfAwz/h2btBhfHjWgOrlTTamhmNym7ng6FYR52+D6xb3sYXwD23ewK5shq6OH+BiEkMW1yVBbSbAd2VbdwD1w0Q1aE83AWL+ETxp2uBukEco7wkHgy/g2mwTBecf1LwjZ56z7z1+YMV4t1m/npDJHif6LpqjtYA9OP1GxBhdSeQM+m8hzmeCLsmYI6g7mmwuoDK68pvwNJSQH7GniXWfgdspeOjAYtj1xRkjGmqfOUbXf9wh/TRucZittWSFu+DUUNLLZAVz/Nc2TeDWvc7W/wZ8c5QLScnCwBPBa3wbxncMaOMjGWIPmgyfGlgiKTzljUuZl523+yZpYD+ZV1sFiWAI73p/Kvs6fJ27jksFfUNNdrYg2v2XjPpsrlq1kf1kbko7pJBV6VaHkprxgfVC4OwHrAOp9SjbIj+L5R3uFrToUgsXbxOdghcljpIAFoWyb1MxCJCAZGSAuVwHhzO28EhD6N5BIEtL9xknRERn4QWr8ismmDRHhcLI80eYyt8bvbYjL8XHNZxfyYiHEyv37IOgwGsQDBB7ImiRrdDbWyhOL1mlV3wfNPrkgV9fPYa/i1Bf1pFF1xTe/BJ4V6noHQCvjBAdE3K0iKtX33qTBzSvhsBdlvFQBEtocaUjRvLEaMbw+7JnCd72ND8sVt+jEkZYXdCb1ErQePrSxwfPrkhfw+IOtmxUBEsLQgbMp6LlAbOPpklOreAuHcTkCo868ef4CvMHrDiy3oqqZu8Uad12kEVmAy9Ksqi5LoUtzg52tFTh0MXFlwiSlnw5+Bicui4B4oGxjqNgZZe3KdPDJBCipn5Wsf39z/9Mu6LNZfz7NIF5BQUYUUKrIOh6XLZ1gvH9lyvXZvIucEra0/qg0ddkL53IP53G88NePuAnVB/9KcQxkHSRE6qUaB3hAF616RkkC4XdlLtXpeb7FDUCwo/flkw7Evl6IpBS2pxFpeouq6tOFaGjoEA5p4jFBFwFL5f2fwf3ZJdBIb1FOeK/RNMR9/bv54n0l7v245oHQkNwR6302RGY5qTazIxl/UfIXwldFAHsYe/tCn4mhknVaqLf0R35Fuy61UiVk2NZnpPU+vK2Tfxk469mQKMW+Ie35K/xMPfqC/f61OqZmH9Mo7wOfM4buVvp+2Jrd2jltG7UCl+h1yn7fpktokoawdO32wH414UKUw8ge8dLy1QlKSvZ6nhNkz4yWE45n9yX0biqeRb3omZ1EQEGEDOwJ1IT2jla5N4gEUOisXSiyf/HxZB/3AmOm6b/TSGjHCuzuqcaKzr68B+c++pOEzh0pMd+JfK8GjM5JtmtFwWcnf9WDYtpVjA/T21Sun3tu3cob+2RjBr6SZAmeNThqj8Nzy/FBHuyiG3ja3A8+QxtnyjdXAJzgDSfQF1GZ6fn3hmSYyXdpQlgaC5sCX41wOuIVN7f76Nh+UdBmyubhmQLGZ7xoP0hRqXyO/lL5DoAfeKtl6HUhJeDkjHGnYeOnsz7HYvyLdt6+1PEN0e79ydQO+QirIT/npmvI/RsQ8n/M1x7T3VWO9jAtFf7DSxVcSpouhoTqxibaNfYPjBv4buMp91uvpCF8gEOQNihuXygWVpGYhW/esananuPDXGzO5fNOt9JML0qO/61yhpzC3iNbwxp69rjo9BqQz+rzktTyPvgSncwT+Yl6Yuu20UgXYELO22UWZ4IbQCmYj8XufxgZsoAERcdRSKNgJTgqFR2cSbKt5wB4XPILoIlv4ZSz656SWFU8RpBK39Wwl50IP0c8bnmEaVofdchLuvN/tgVKw2ooa8celeQ6EKJl3hRkisDdp2Q0af5RyTMc3KEL6haY31Dbt6WUkLHxWyeIZlbRY1Tggcr2OiOs1L5zzA75XcW5T6NNLryHsyP9S8q8ky/LR38W7D4VAI4lw6tyJsHFx+BvWk1EPgdrNIRJAT7ynT3pvPH3F8GW6jrm1jYn9LYN3UFkq2oiEG75KuNIyWFj9ymluWXRRUn2MpZEbVzq9uBAecKqmG5UIbEbnThxKpCZwLrQUI1j5OR8fxQ2WKB79KOiedRm0shAwCp3BsKo1Bu9fju27gJOSEiko91ns6qtOXlushfx8xaY3Vatky1Xy2bTSH+OeSqVbvQm3oxJNAE7pHQxsh3gWvyedaVyz5/Mu0NoNIERqP46AGZYEBm8s7bdm64VdChfz9kuU7Yuj5B+/PLtnbqkSxLBAF9p29Uj8AZhfg/bIOdYdq+7SOjkjNGk42asXzZuZcRcA2qiaQsmSW0FtZDJ7G4tc7Xl3htRXoO1m4gKjONCmZLflEOl5N7jHyMt+n9CXyLrjh8YquZGd0U0PNa+mSSg1TOdyjrkz4lSq2/8YXw0UrGww9mOjNhEqQsOY4zM8acTwM5fkAl9xsG999kJhVn8GBAUVQc0pzsG2iMZ8wc/epGk0IH7AXykd3/Sh0lMVNkpWEhDFQRKCjiqdI/+azol+EER+/om74IHlYIs3dAjI1AI99DywYErXdLIofkppwAj9YkY+aQhfKqFRBUlgC3xbevFTb2WrdunhNwwm7rqRFroQyipKrRtA+wrbPXHV9jJtr7NtXd9JdfMjyZxK78hWZsGPdecnz34QWs0QnQh+JDVHDCd8HMAlXrK9phXAHCmUzFFORNH79u5WBZZrIt/UsYnwUj5Xx9MAHmrQx++SWvsqnNSJ1jHml0tcvbZNCahYIxlzG41RJaMVF9MBW5XTLH6Tat+j9FKy+kOyHH7S9ZtrHOBARqUE8BlSfgL1pu/1I4OeKB5LaBHq5CW35rphUjZ8Rtfbtv/P9cLnArldloNqVEG5rowWNbVciMwjHq5nYTwq9RxZpxs7515P//14lERvUDQtIDDnQojdiby7hgC87tcApXh/rn/Hgc9ev6ET1KLaV9+G2+TeA2v+NBHwLHN4pd7KZ7wcXlYTtPahdQgnKWOlFqDrml9fNJt2VNxAJykwSiMOiliQONVMK4AUwVtfek7iqREBvKkESbPSADE3lCy07dgSty96oNRUsEugukjGeSqYM8BrzpkNzyce6wxzb8xwcK+zxv6FRg3pQO1De4lGkWUAsT8jo/GsSYiBdOHU80AlkNRihXa56zDcKpwEePIZLWjgMzqANjbQ5nDMVRIZgSJCNcfRJqVn3pgTuyhiQL4niKehQwvD2N1C/BwLO+E0pdeunssuAM1PJ34Vzn3NRACbKHPKHr6W2mjYRbdF61y/5HfSetJz843yC8N9DsVrlL7mfaBLTcFzOCQavOIC8NYX1gL1jbURS5Bz9DI/NmPGEe11N709Sm+jjlFixj5qmq+/2dRIN9mfPaazGkOMPUiAiOXlvUyLCdhYdKXqCwo0GaYnCHn4sL8L0Vf25rxEXgzKkB6ohUi/E+uWtfvS2ua5EHBSEdCLKelBFrEC8wvq2NO0H3GmzZtNqwj29gNuSPu2VOzYZStHbk17ZmQ97leY8Sb6ogXpxHSEMiRA7oUtUB3mDwJPbi0/bLMCP6yjphFssNg1sBL196zBKQEIEXTlc2gUKawnOdlVG4eDlgIGfuZJgRyf6ro/5/XDXItRhkDr8nm2Mma+FxrhCCNuTr+znh2FykHw9S1V9mYIsMOm8tryA4hHuJD1DaBmxKNtGXyWg8Y7CO0orBl0FpTxAPzMPu88ToVis8o6z5kkhjPmwZsp9r6xx86et9Zd76wim/6kpkxchE7fSK1GjrNLnRawuDdiyc3Ql5PQon2Gd9TCLHpl7/7s8qXiS4RGlp8oYeEkUhIBxXj2tdgU9rx41AOoLRa9BxdvfzE1fHIOWJpoPqPHnGpmHqX1Tx4yZzyv3jhv9K7nmxAwLNtKfyOaIjzuAf97DLzswKsV7fHZ2gmM4cJeXMWu3CJzn5IVdF04nPf0RoImG5r8r7J6IZlWsY3f9KVE39qSAHroXpM0UUCvDXln9LhQiqIvl6m1Z+rNjNqnYLVDajd6EdKSdzPtTg/dBUkhIPwjTXY5zojDO3h7Ao1Ueb2//T1yHd56buZv8Zptc9R949icm+mbiZ9oXlDpvMw9fYO7QNVt59B2omcoEIwskwn7HK9novle54e3qbltq5tlN2sO0SyS5PUCf0H5F5j410xqy2bEIyOR4KhQpl+6ngaXHJE31HqGDBe0T9FNV0LkkhAZV/3QkZIR4Q2Z9t1zicGb3PTVM8cQhq9Fy1onGuy5Cs9V84XZA+Itj9S7hfhoueogLb8t9NF2X107zjCQ1b9G070tgX0fuE0xD8yNEYZO9vS6JX5KoCFXwN6MEYZCVb76OUCC2yHROSawuk+CBPIaEv3A+lzLQGo4O/k6ExVoIqPxFUAWBSNLd,iv:3tPRSLRCiPDSoqZ+B2KBHiZsil5njHx3YJWH214AYeY=,tag:1Zu5kir9vEg1zSDQrSuXKw==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM09IdnJEejNkQkZ3Yzh5
        SW05M1dQak5PRWN0eENIOGU3cEVBZ3VYNXhZCnIxV3FlcE9TdGZCdmlUWHJIK0p3
        bmtQWWhJVm9kM1o0NXM2dFlSS2xiME0KLS0tIHhDTlhEVFJuWXFSa0Jkd3h4Y2JP
        SzBDcTV5U0pzSFRxbTNCVElHVm1BVEkKdLFk1SONr7goJVo9XiyeNw4hFTZZIuQa
        bMCii8Umb4D48Ov7Yiv2y5yx7LZU7joYqdsvR8FvDvR8ks/MKyIoMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-12T13:28:26Z"
  mac: ENC[AES256_GCM,data:Rfj3rkItxjYByMn9n16I8K7F3b0PQQC1M4UymNoIbgXzAH+4W6/6DCuIKfX6liRDabE83R5CUNbRZkNZO4ZtDGdE4M4hgk1RW8jqklZ96qbXoUcqVUqZcd7vDNrAtgZOLztJvuez1eCz3H51eEFwIcRUS7ByKJZNsdJJb2SCwpc=,iv:9hgp3nuA65sUcn9/msF+jS9raT6M1aio88X1WIMbIws=,tag:/XniugnLlCgZQ1FZEByVhg==,type:str]
  version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    reconcile.fluxcd.io/watch: Enabled
  name: prowlarr-config
  namespace: media
stringData:
  config.xml: ENC[AES256_GCM,data:PqO3SrkWmmKaGrA+emb4IH8xq9vCG7qPmdYuOt1rNwVmItOkljj7vq7G53cSEt6di1Q4MIjw80UBSa/byse9FOMF5ZkUSXPkUhYRoCp5+I21isiLQwo1vbGADtYcf1higTJ2+rHthgjmGvqgDxXcX9ZYPoiPQZfCLOvOnAtxNdxAM4I+06LdBprj88yz2WhraNenm8RAQ7Kx0UfFkJvCDHjalG7/HoEmjoqTI3KpZCqiYHdmlFLZdvF5RJkgE2t638QXZ22dKPp6an3k1gQ7dq8SxiIJglmBN9v/vfk8oIXgRWIOkvwktF+ih0vcx+Faow2rTcTyQ7aFYRbc8HalBmhK4TI0DOcEww3VHk4HOpdGPYbXA02rNtZ8Xf7icM8hQ4BUuSD6aGYH6DdsBIjgKSArhQLGIxRFsk9Q86m9chd7LEHK1XvLEP+Ygpq2JaUniaDa3hlDky6V0XbHmB+4OoyADt65kuMjO4mApfwgVNZTHSVmzG2ISb0KPbt5QzjiDV+vmibh2qTyCiiSTkTxvWc8ldL90Rnzw/kxYcg8jHSDjVbu73NwWGGMIzNvWOJNLay0SkSjE/mn5pim6X48D93qPqu8zLODaoRQTBaq/Q6Axpl8yoO0hSO4Lix6MVT48gHRKZ7M3Wkm/Ci+2EesO+ldtaOWC1EiZnGJ+qJFjSYKApCD2SYO/JGmifU+O0hja/DGR4yLpDFimCvaBQ1Pn9FBELzbUMUkpMqzKyYNvw8taUl4eQCsHQbf9IDJ6ZAlI2o/swrZHwva+udOL+l8QJA9RSJOTYS2z7xDIAmZyBIARelGwyT8q8ImXJ+trzj3I99mVE22WHou1R2U,iv:v3fpIygoMS+KvsHimHHAtPt4F08Etbezi0nVBUJXlFE=,tag:3TtHap0McyVz0F0RsEbAqw==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM09IdnJEejNkQkZ3Yzh5
        SW05M1dQak5PRWN0eENIOGU3cEVBZ3VYNXhZCnIxV3FlcE9TdGZCdmlUWHJIK0p3
        bmtQWWhJVm9kM1o0NXM2dFlSS2xiME0KLS0tIHhDTlhEVFJuWXFSa0Jkd3h4Y2JP
        SzBDcTV5U0pzSFRxbTNCVElHVm1BVEkKdLFk1SONr7goJVo9XiyeNw4hFTZZIuQa
        bMCii8Umb4D48Ov7Yiv2y5yx7LZU7joYqdsvR8FvDvR8ks/MKyIoMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-12T13:28:26Z"
  mac: ENC[AES256_GCM,data:Rfj3rkItxjYByMn9n16I8K7F3b0PQQC1M4UymNoIbgXzAH+4W6/6DCuIKfX6liRDabE83R5CUNbRZkNZO4ZtDGdE4M4hgk1RW8jqklZ96qbXoUcqVUqZcd7vDNrAtgZOLztJvuez1eCz3H51eEFwIcRUS7ByKJZNsdJJb2SCwpc=,iv:9hgp3nuA65sUcn9/msF+jS9raT6M1aio88X1WIMbIws=,tag:/XniugnLlCgZQ1FZEByVhg==,type:str]
  version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    reconcile.fluxcd.io/watch: Enabled
  name: radarr-config
  namespace: media
stringData:
  config.xml: ENC[AES256_GCM,data:DVqYV6s4edxrI7u6kzvqNzU1as19D3zfppZt5Q/Ridkh4AGGpuw/uKwzKJ6GXR4k+sTEino9HVOkDTglTWZbDsvAxZQf2fF6/OlBVaDgVUCE7vlriHpHT4s7b7c1x9mtAoLwSD1MTbGfGA3SJHFSGJvis2R1oOqRnvKUBwljo24l/YADQGZaL3ugPjMaUeivRvm1q2wMKB/pDOJa6JILS6EefIueENXwYPvSCAyO5EdX3cK3tJNEdZqUcP/SRMKyz//ctj2kda3EPiB/m+nxy5WUfvpcGGhj+n2hD3TCFBwe9w82tAKSOWU2+/UOImZ/Z20e8dfLmZnCiaq5dNyMqyQb5imSb6JmtHOW4SqEU1KgBbCRGAnBWe0REIglXs+twPhQGE1i/MXkwU7SUp3rkEoEo6LjnCbkr25Ga0+zcLEi/cDmxWmYGcKNXzFht4MSPJz7w5Ua4A+Av+Diq2NWEwlQGmmbME+FXnIAkEMvkXkcASSm10o2TmjGXItocm05VS1GHr27ysdR/Mwg82/hHqXdQBZ6Ymldc/hoQo2vkCEarFDghRXXqGXuXTmsQG9C1gdfRBIqjNMPIQ4u1DmJ2kjRFqC/13oK33pD/aCrIq1v+XEVwaZ/Dk1i180e91hPQXToHDRuN0dsOROt85vRP8JSPRQVt1W/GCnn3mi6/3M+MhaDCOZQWrP0ynSQGXEejVWCVkz6mQ2p6PIzVonBxhOVaN95e8RDd47PFrbEQMtLbnRuC8U+IPhRAUE5RkwlwG0YYoYnR1zwhkLm1pQk807TRc2EYhXGf46TPjR/BlAgro5ZwXtuhzqPlTt9vFTTMr4TiBUmk4C1aqOmByD9YgABHWGts10SX5+kk5MiiQ18QpR90WCulRMxWY6uycEJHfpwwHQpLQ==,iv:JWgaO8vdR3XYHQA+A6rNPC4+6vBAnqJy36SSDWdpPU8=,tag:tp3ijxPX60ek2sfeIFqBtA==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM09IdnJEejNkQkZ3Yzh5
        SW05M1dQak5PRWN0eENIOGU3cEVBZ3VYNXhZCnIxV3FlcE9TdGZCdmlUWHJIK0p3
        bmtQWWhJVm9kM1o0NXM2dFlSS2xiME0KLS0tIHhDTlhEVFJuWXFSa0Jkd3h4Y2JP
        SzBDcTV5U0pzSFRxbTNCVElHVm1BVEkKdLFk1SONr7goJVo9XiyeNw4hFTZZIuQa
        bMCii8Umb4D48Ov7Yiv2y5yx7LZU7joYqdsvR8FvDvR8ks/MKyIoMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-12T13:28:26Z"
  mac: ENC[AES256_GCM,data:Rfj3rkItxjYByMn9n16I8K7F3b0PQQC1M4UymNoIbgXzAH+4W6/6DCuIKfX6liRDabE83R5CUNbRZkNZO4ZtDGdE4M4hgk1RW8jqklZ96qbXoUcqVUqZcd7vDNrAtgZOLztJvuez1eCz3H51eEFwIcRUS7ByKJZNsdJJb2SCwpc=,iv:9hgp3nuA65sUcn9/msF+jS9raT6M1aio88X1WIMbIws=,tag:/XniugnLlCgZQ1FZEByVhg==,type:str]
  version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    reconcile.fluxcd.io/watch: Enabled
  name: recyclarr-env
  namespace: media
stringData:
  RADARR_API_KEY: ENC[AES256_GCM,data:Ib2gnwD2Df1nbSfSzvQbIm4lCW/O3FrHYGIckFmzrVI=,iv:KGJHKOu802HCfRFqEDvg/OyjmjgVUSs8vPIv3SflsTo=,tag:h6mjLW3jtvW5tz1hUOoDBA==,type:str]
  SONARR_API_KEY: ENC[AES256_GCM,data:3Ch4Y596ElbrScu4H1zghg98DsRy/a+22VNfVojCmio=,iv:pB3ZLZ0szHZ5a0bT1OSkioVIy9Nwd+n0Z/SF/8xkKtI=,tag:s1LfeB2k16dbx54pQ5Mm6g==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM09IdnJEejNkQkZ3Yzh5
        SW05M1dQak5PRWN0eENIOGU3cEVBZ3VYNXhZCnIxV3FlcE9TdGZCdmlUWHJIK0p3
        bmtQWWhJVm9kM1o0NXM2dFlSS2xiME0KLS0tIHhDTlhEVFJuWXFSa0Jkd3h4Y2JP
        SzBDcTV5U0pzSFRxbTNCVElHVm1BVEkKdLFk1SONr7goJVo9XiyeNw4hFTZZIuQa
        bMCii8Umb4D48Ov7Yiv2y5yx7LZU7joYqdsvR8FvDvR8ks/MKyIoMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-12T13:28:26Z"
  mac: ENC[AES256_GCM,data:Rfj3rkItxjYByMn9n16I8K7F3b0PQQC1M4UymNoIbgXzAH+4W6/6DCuIKfX6liRDabE83R5CUNbRZkNZO4ZtDGdE4M4hgk1RW8jqklZ96qbXoUcqVUqZcd7vDNrAtgZOLztJvuez1eCz3H51eEFwIcRUS7ByKJZNsdJJb2SCwpc=,iv:9hgp3nuA65sUcn9/msF+jS9raT6M1aio88X1WIMbIws=,tag:/XniugnLlCgZQ1FZEByVhg==,type:str]
  version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    reconcile.fluxcd.io/watch: Enabled
  name: sonarr-config
  namespace: media
stringData:
  config.xml: ENC[AES256_GCM,data:55dRhUuB2/UuVw780dex5O91pItOBCwRXDQgRGRLFwYG1zYSbfN0oLEla184717QgzMaC4Hj3d3eGmLDsGkusOx/40BzmgBzu4F3HOvkeoROVgseu8mEip4Xw85k8E8JWOtLh8aCTLqhLKk65bPW2/m/C0fc0SIrQ/FsTGIctzeXyCyTLaMvvCxZUQXWYJLa3KgWYs2/YTeZo70wfn62BXkutyf+9BgF3HKGo9aNuxS1Bh9izJG5Hg54pFbtAMKGB2AmVNvhm+/7LT1tQT/vTaPNnA3UmtM9lk0x9Chp8vZJE6t7itWx2ZoW/cGTo9fBP5HlaWJttV7Gjo8O/bkzIRuZNzBXRVwklSWx7j0fb6xHzdn0giDMvLjsN1lWWLhA4lGMmhuAzi+ijF8BfnMjLgm8JyDylyLWEaKfrs9WRPRXU6g3gtdqPBiHogt07R+ThSK5xhU+WG1JuVlPyB/LW6kxD9SgwQeeRx2FYuyP9yk5zDSusb3zQ7QowHSMdheZrIDhknuL7/ubmyJvFadtzjLwqYypjKX7PcaUgz8Ro2XeKQKx06Sj05sHHBrGXvmUKHKf+F+l7Hn0JCBxa70XeMb6HsifJNc0WAGoVbAdfdyXgHID8pwTshG4fDdFcc1+Fzv2yshzgwXmcBbfr4jB/5Gv8W9KGHI8hSfS/wdk3ox0Yz71onD4EH/yzYqwjXRkX6M2MPajQvcTTZh2WbQVALWJ2F+tvWm5lnBXF4nbFOACx06CsvvGHuY/ClMpXwnpMaik2229rEjc7KsPrp1nDjiQ+kWTMwIFHnU00k6OqxBWtBDjL4xmmWMYx4HvncPoplUoojSHURGYcJoDZdLTEtJ238qZ3dWIDgRtyDXKjmSmHQVO7Jgi+6gXOXWKhTos5XJ7f3Q=,iv:ZnZX8ciw94mVoUGLRMdcxmMnwyMGvl/skGueTwjf4kw=,tag:JDSTrHbQxqRFXrLbRmcUTA==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM09IdnJEejNkQkZ3Yzh5
        SW05M1dQak5PRWN0eENIOGU3cEVBZ3VYNXhZCnIxV3FlcE9TdGZCdmlUWHJIK0p3
        bmtQWWhJVm9kM1o0NXM2dFlSS2xiME0KLS0tIHhDTlhEVFJuWXFSa0Jkd3h4Y2JP
        SzBDcTV5U0pzSFRxbTNCVElHVm1BVEkKdLFk1SONr7goJVo9XiyeNw4hFTZZIuQa
        bMCii8Umb4D48Ov7Yiv2y5yx7LZU7joYqdsvR8FvDvR8ks/MKyIoMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-12T13:28:26Z"
  mac: ENC[AES256_GCM,data:Rfj3rkItxjYByMn9n16I8K7F3b0PQQC1M4UymNoIbgXzAH+4W6/6DCuIKfX6liRDabE83R5CUNbRZkNZO4ZtDGdE4M4hgk1RW8jqklZ96qbXoUcqVUqZcd7vDNrAtgZOLztJvuez1eCz3H51eEFwIcRUS7ByKJZNsdJJb2SCwpc=,iv:9hgp3nuA65sUcn9/msF+jS9raT6M1aio88X1WIMbIws=,tag:/XniugnLlCgZQ1FZEByVhg==,type:str]
  version: 3.13.0
