---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/media-server
  - resources/ingressroute.yaml

secretGenerator:
  - files:
      - config.xml=configs/lidarr-config.sops.xml
    name: lidarr-config
    namespace: media
  - files:
      - nzbget.conf=configs/nzbget.sops.conf
    name: nzbget-config
    namespace: media
  - files:
      - config.xml=configs/prowlarr-config.sops.xml
    name: prowlarr-config
    namespace: media
  - files:
      - config.xml=configs/radarr-config.sops.xml
    name: radarr-config
    namespace: media
  - envs:
      - configs/recyclarr-env.sops.env
    name: recyclarr-env
    namespace: media
  - files:
      - config.xml=configs/sonarr-config.sops.xml
    name: sonarr-config
    namespace: media

patches:
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - lidarr.home.arpa
    target:
      kind: Certificate
      name: lidarr
      namespace: media
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - nzbget.home.arpa
    target:
      kind: Certificate
      name: nzbget
      namespace: media
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - ombi.home.arpa
    target:
      kind: Certificate
      name: ombi
      namespace: media
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - prowlarr.home.arpa
    target:
      kind: Certificate
      name: prowlarr
      namespace: media
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - radarr.home.arpa
    target:
      kind: Certificate
      name: radarr
      namespace: media
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - sonarr.home.arpa
    target:
      kind: Certificate
      name: sonarr
      namespace: media
  - patch: |-
      - op: add
        path: /spec/template/spec/securityContext/fsGroup
        value: 984 # library
      - op: add
        path: /spec/template/spec/securityContext/runAsGroup
        value: 984 # library
      - op: add
        path: /spec/template/spec/securityContext/runAsUser
        value: 993 # library
    target:
      kind: Deployment
      namespace: media
