---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/media-server
  - resources/ingressroute.yaml
  - resources/secret.yaml

secretGenerator:
  - files:
      - config.xml=configs/lidarr-config.xml.sops
    name: lidarr-config
    namespace: media
  - files:
      - nzbget.conf=configs/nzbget.conf.sops
    name: nzbget-config
    namespace: media
  - files:
      - config.xml=configs/prowlarr-config.xml.sops
    name: prowlarr-config
    namespace: media
  - files:
      - config.xml=configs/radarr-config.xml.sops
    name: radarr-config
    namespace: media
  - files:
      - config.xml=configs/sonarr-config.xml.sops
    name: sonarr-config
    namespace: media

patches:
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - lidarr.***REMOVED***
    target:
      kind: Certificate
      name: lidarr
      namespace: media
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - nzbget.***REMOVED***
    target:
      kind: Certificate
      name: nzbget
      namespace: media
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - ombi.***REMOVED***
    target:
      kind: Certificate
      name: ombi
      namespace: media
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - prowlarr.***REMOVED***
    target:
      kind: Certificate
      name: prowlarr
      namespace: media
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - radarr.***REMOVED***
    target:
      kind: Certificate
      name: radarr
      namespace: media
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - sonarr.***REMOVED***
    target:
      kind: Certificate
      name: sonarr
      namespace: media
  - patch: |-
      - op: add
        path: /spec/template/spec/securityContext/fsGroup
        value: 984 # library
      - op: add
        path: /spec/template/spec/securityContext/runAsGroup
        value: 984 # library
      - op: add
        path: /spec/template/spec/securityContext/runAsUser
        value: 993 # library
    target:
      kind: Deployment
      namespace: media
