apiVersion: v1
kind: Secret
metadata:
  name: pds-env
  namespace: pds
stringData:
  PDS_ADMIN_PASSWORD: ENC[AES256_GCM,data:yMxxNSpHA2VHbxZdm+uf573+pJ4E3EGHNqRD+fRDKJE=,iv:pLxb8SGZ+zWqWeGYYjSFUWMg3g1xWAuKHkOSkJg3dSE=,tag:vLGgbPvTuXLfTH7lN1Nnzw==,type:str]
  PDS_JWT_SECRET: ENC[AES256_GCM,data:ybHAoS4dE2TXl5kWuhX47wka40d5nCgD4Uc/1l2s23s=,iv:TRxsAHVrp67gfykd7TitZbAdN81X0NfXvn0lOhOVVFc=,tag:ytsktExEcQwwD0u5Pok6nA==,type:str]
  PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX: ENC[AES256_GCM,data:fIED3KvhUcgLNxBA6gw1/CpjE5gumITT8zt3KU6teCBi7af3sgu3vz0AGFdSRfneoCluAol0T4vrhpQUjq3nAA==,iv:x9t6JO61fI4R+0Bx/qp8fzPxlsPcvr9YUdYBTjG17ak=,tag:b1O+K6MlMR4go4ExAeiW9Q==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aDVEcDg3a2RhU0MvUGRY
        bTU4blhQU3pEaHQvWUMwZjRjWitQcGU2TVZnClBqczNPdWxDOU1CMEQ5NmN6dUVh
        cHdvT2dDK1dhTDU4azlseWVxUmo4U0kKLS0tIFVMUTJBbTJFMUI2UDlsMjJjd0RN
        VXphSmdIQzYwbTVBbVJmWmd3Z3VlYUUKwWSIZ44Xz5yjjm6ku3P2n9oV4I+myx2A
        QzgrvydEu8KPEM+6c+ZQTzG5ULp5qEbuUdW4y04MdvPmoYADxtvcLQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-13T18:19:37Z"
  mac: ENC[AES256_GCM,data:rePmVvaByIT5RQ9ubsKgNF/MjeJE7gx39R2R6kH5BVfR/kLI8VwCRZl+4sRCbwbTHPM5i7CkKJhCbrnFhqyOM5TU7dKhjut59aeOnL2pr38yPebAGZrON0MFTiNvZjF5vqBbBg4ewZcKVhIkAlJ3LHjpmYoZsDcfwfM1Pn+c/5Q=,iv:w7cnuB3s+3vu9Cgw2x3vzTk3iLOYp0GYGvIyqG3+ndU=,tag:EhGMMDiCFvtAo09n8K9+Kw==,type:str]
  version: 3.13.0
