---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/certificate.yaml
  - resources/deployment.yaml
  - resources/ingressroute.yaml
  - resources/middleware.yaml
  - resources/namespace.yaml
  - resources/networkpolicy.yaml
  - resources/service.yaml

configMapGenerator:
  - files:
      - configs/nginx.conf
      - configs/redirect.js
    name: redirector-nginx
    namespace: redirector

secretGenerator:
  - files:
      - .dockerconfigjson=configs/docker-hub.dockerconfigjson
    name: docker-hub
    namespace: redirector
    type: kubernetes.io/dockerconfigjson
