---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: immich-library
  name: immich-library
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  claimRef:
    name: immich-library
    namespace: immich
  iscsi:
    fsType: btrfs
    iqn: ***REMOVED***
    lun: 3
    targetPortal: ***REMOVED***
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: immich-postgres
  name: immich-postgres
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  claimRef:
    name: immich-postgres
    namespace: immich
  iscsi:
    fsType: btrfs
    iqn: ***REMOVED***
    lun: 4
    targetPortal: ***REMOVED***
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
