---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: immich-library
  name: immich-library
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  claimRef:
    name: immich-library
    namespace: immich
  iscsi:
    fsType: btrfs
    iqn: iqn.2000-01.com.synology:diskstation.default-target.8f20388e135
    lun: 3
    targetPortal: 192.168.1.3:3260
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: immich-postgres
  name: immich-postgres
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  claimRef:
    name: immich-postgres
    namespace: immich
  iscsi:
    fsType: btrfs
    iqn: iqn.2000-01.com.synology:diskstation.default-target.8f20388e135
    lun: 4
    targetPortal: 192.168.1.3:3260
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
