---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  ${DOMAIN_NAME/./-}.server: |
    ${DOMAIN_NAME}:53 {
      errors
      cache 30
      forward . ${LAN_IPV4_ADDRESS}
    }
