---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: !!str false
  name: synostorage
parameters:
  dsm: ***REMOVED***
  formatOptions: --nodiscard
  fsType: btrfs
  location: /volume1
provisioner: csi.san.synology.com
reclaimPolicy: Retain
