---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: pds
    app.kubernetes.io/name: pds-data
  name: pds-data
  namespace: pds
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 1Gi
  storageClassName: synostorage
  volumeMode: Filesystem
