apiVersion: v1
kind: Secret
metadata:
  labels:
    reconcile.fluxcd.io/watch: Enabled
  name: runner
  namespace: gitea-actions
stringData:
  token: ENC[AES256_GCM,data:0o1VO4tmhf3nwUaQI9Afo3nP2q1r/wAd16quOmUUW8Q=,iv:mQS+gWPHZl37TxK4ERjKkruEm4bejf6nd26m0b557Po=,tag:3WdSL58ZucREAAYk4jGhZw==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM09IdnJEejNkQkZ3Yzh5
        SW05M1dQak5PRWN0eENIOGU3cEVBZ3VYNXhZCnIxV3FlcE9TdGZCdmlUWHJIK0p3
        bmtQWWhJVm9kM1o0NXM2dFlSS2xiME0KLS0tIHhDTlhEVFJuWXFSa0Jkd3h4Y2JP
        SzBDcTV5U0pzSFRxbTNCVElHVm1BVEkKdLFk1SONr7goJVo9XiyeNw4hFTZZIuQa
        bMCii8Umb4D48Ov7Yiv2y5yx7LZU7joYqdsvR8FvDvR8ks/MKyIoMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-11T17:04:09Z"
  mac: ENC[AES256_GCM,data:dHx7xbrsKKlZviEhOhF6JZAOC40MzVYUJJr2BXuhLVz4UDpuz18iBNqSEJNJMgV4uWysWM9eoRP1AGmhVYRd8W3LpEiPwb46PCJHVECmeHoqGUik5/XzflcoQZnV5mnalVu3jqFMdAH2y9vyiKdeTp2IZqxprWCUmEmxL/LtCBY=,iv:CTftxjpAcj/gWd3KMhsOkthnTPk2JEBDhL7UIORasgA=,tag:EejfPRo0Zh8+Fjb7TUUSNg==,type:str]
  version: 3.13.0
