apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: runner
  namespace: gitea-actions
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:QRKhbzlw,iv:rglUXHbYhboN+rpQHHSmNbkx/bBrX7g0IMHJ6WuPTTA=,tag:TgC824smhdwkegcVQafhAg==,type:str]
      stringData:
        token: ENC[AES256_GCM,data:V337gosZPpI24LMj0WoOT4LIBhQyLvmN7pTSDLT86BU=,iv:DugVH2w8zf5TL0zuoBn1M5VrCeH9gvEFGNq5Ra8Jyso=,tag:4KlbwUnIX+JCSBHrRtq65g==,type:str]
sops:
  age:
    - recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RFFsK2xlMUlDTklPUmVM
        RnJaaXZLTjh3VWZvVXhadFF4SXBOczNrV0M4Cmk3eVZDUStjb2JWM1gzaFFBeGFF
        clBpZU8xVTFrOVhnQTY4VCtDM3hkaTQKLS0tIDA3YjF1VDhLNkpXb2NsREJEMlRn
        UHJVb0w0SjkyY3pJcUJjMjNQVUJIdlkKr/iu2QIdmEsQBlPGgAJEDmfdC5GXiGHk
        NqWOaDJN5OLc69RChUmpngXuzLuXRGFfL6EqhBZUIw3EjxC85OMVkg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-04T06:53:02Z"
  mac: ENC[AES256_GCM,data:EsZckrErJgt3snriiMeQ0Me3SEdBFSzz6hqP0m9P9ovpVIO/14SdMLzHT4li0EX1xotA8yTtYSeJN/KQ7b4LPMPTB+JuXggRCGEgIKiLu362qswt1WlZFh5qa8qQp1JwBAV/TlSkUGt8lOR2+GNkBOdoZdHWHr4XXgCXIDC0uwE=,iv:u9Hqzv6kbLuu8o2f2FHFIbmUDPJimV9p1KOHxCcghyo=,tag:mLdyU6L8lG9yDsZrV/Nmkg==,type:str]
  encrypted_suffix: Templates
  version: 3.12.2
