---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: openclaw
  name: openclaw-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    name: openclaw-data
    namespace: openclaw
  iscsi:
    fsType: btrfs
    iqn: ***REMOVED***
    lun: 3
    targetPortal: ***REMOVED***
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
