apiVersion: v1
kind: Secret
metadata:
  labels:
    app: openclaw
    reconcile.fluxcd.io/watch: Enabled
  name: openclaw-config
  namespace: openclaw
stringData:
  AGENTS.md: ENC[AES256_GCM,data:bP8uqnuKdzhR6GBxc9UXBn81geETqmf7Y9seDzmJYYjZNaDyeaEw9Y/r57mxvgDJR3heAPws0fE6HpmHXACDNjf6KGzBZU1bhEzUgQ==,iv:aeA/pArMYBl/poQJSt3IXweyORhnmSIBcZVp9dILWsQ=,tag:UMP92tTSVid+eyOXa242Ig==,type:str]
  openclaw.json: ENC[AES256_GCM,data:cYZVBginC+etA1kt64GKTNllcPhuX3+ECPZBwgFgkRzVDAX0/vZ9Lb1yVFYunFVddADJ9JJ55MakYY5R78MJNEyLALL5FgLqbpR5D7mcfMYm0wQJgbBs/bAPZiXCxa8emekpoxFMXZawA4fpujqAQ/KgQxKYyFMnxfO6IY6BpGknp2Jmbuazf+q2OKuoIZ11vMfFra/4OGwapgR0ie1OKeCp3jTNuEAXvdlgU1/oWqT0SptsVzfeIZapEuZUHMBFuKdiYuvq1MUHr/KifS9raBPJV02j6THVr31cVdYIQjdaHNbPktyXslvU/qUMpdUesHszIzKcgIF7KFVESBcku2PZ+4uI7te4n/PpljOv9SR8X3w0I83xUiQI6SiQ4VgV62YTseDDGwH6ZmCYw6vGIDukF27XxIYMmt5mcuCByCUL7D48wbLe43932M6tHDqRKoDTKQPjARV8ACV60OtTA/TwY5HZ0dqxs4mHV6QH19K8Z3d7636ajRlhAGIsX5nBjkr6TqV2QhwByQkfH5oAEyc8JSbVY3ZnJ+IvakIlB5g51fseTv3f3v4J2GGCzkQmiVFT1l9h0RT4uLezSI27a1V0WT4PvU9qJUC+eCQX3UPwiG/qSG/UFG6Hc8AckZmg+Rfb,iv:OAvF/CxPdX6TlvTNALkvr0ZzExCJ5QgEyxRUHnHQgHw=,tag:7Rn7L2cbAbUtfBAcwByktA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eVBJUTY2dDdaK1pOanNv
        UHpienNsZTEwQ3dVOTdXY01qSndFUXNyWVFnCkM3WEJyckZUNG53dWQ1L01EZ0h0
        bGpaWmR6TkVqSXh4bVlBZ1hMb0RjZDAKLS0tIGRxODNtKzVMSXVQU2pFTEhKQU5B
        NVMvVHd1cHNZbjdIUE1FcENGdXFZcGsKKOQrkiiq6fdsgvFod06paXzW7960nuOE
        J9kBg6lTpmc4N/G+5AAOEatyTCwsSVU6rvNzr6/Wqk9iFswP8qnt0g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-12T15:09:19Z"
  mac: ENC[AES256_GCM,data:igYwyVNlTnzEopdXxy24LIIP7W5p50zRFG61a98uLIwdDjNlnpB3COYs1Qme8RDZJd4uk20bBFZZM2jw+9vyCylXKRyNtE0D3arRZaNx/aPf0DKitmeYWA4toNvmpqKLqZwjE3EfRl1QnchgAqTCNnrT7GOZZlkqFIlvbtJ2+m4=,iv:rrxhYfKtwelOIX3STynryUBWgqkoMpu2Ooeph8QbWb4=,tag:+ts6e+z3YM0GQyzhBxLIIg==,type:str]
  version: 3.13.0
