# yamllint disable rule:line-length
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: imapfilter
  name: imapfilter
  namespace: imapfilter
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: imapfilter
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: imapfilter
    spec:
      automountServiceAccountToken: false
      containers:
        - image: ghcr.io/nosborn/imapfilter:2.8.2
          imagePullPolicy: Always
          name: imapfilter
          # resources:
          #   requests:
          #     cpu: 1m
          #     memory: 8Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /app/.imapfilter/config.lua
              name: config
              subPath: config.lua
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: config
          secret:
            secretName: imapfilter-config
