---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/deployment.yaml
  - resources/namespace.yaml
  - resources/persistentvolumeclaim.yaml

secretGenerator:
  - files:
      - .dockerconfigjson=configs/docker-hub.dockerconfigjson
    name: docker-hub
    namespace: gitea-actions
    type: kubernetes.io/dockerconfigjson
