apiVersion: v1
kind: Secret
metadata:
  labels:
    reconcile.fluxcd.io/watch: Enabled
  name: searxng-env
  namespace: searxng
stringData:
  SEARXNG_SECRET: ENC[AES256_GCM,data:wCbhITjvrj0G8VC4qABeB6i4tGkfoczOFNup7oUkDHA=,iv:Zu8DVc+3GzjCTpL1smG3Kb1NthD++kOGTENg+xIxEio=,tag:AoEQSFm/uVjxs/2SmxxQbQ==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM09IdnJEejNkQkZ3Yzh5
        SW05M1dQak5PRWN0eENIOGU3cEVBZ3VYNXhZCnIxV3FlcE9TdGZCdmlUWHJIK0p3
        bmtQWWhJVm9kM1o0NXM2dFlSS2xiME0KLS0tIHhDTlhEVFJuWXFSa0Jkd3h4Y2JP
        SzBDcTV5U0pzSFRxbTNCVElHVm1BVEkKdLFk1SONr7goJVo9XiyeNw4hFTZZIuQa
        bMCii8Umb4D48Ov7Yiv2y5yx7LZU7joYqdsvR8FvDvR8ks/MKyIoMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-11T15:26:02Z"
  mac: ENC[AES256_GCM,data:xjGooKLzBE0DSnO6yiuRuA7c6XG09h/gzjzrjhKmWa+1vWUHRrQmakhWOgWx8dx5pRAaCwktwLLbI02KnzBRYcmezGQO4RCH4PSD2muFuOcOYcdty/1UGfUfV79WzKHINovKqJK2MKHC6wEilhc6wjGa9IKKWJc3r87HRHrXPbQ=,iv:jfeGh9+oi1FIHRxKkaT64AG0ZeZP1q1kbRCGlkv2CSE=,tag:ZhR3df2aatW1jMLqKv/Gdg==,type:str]
  version: 3.13.0
