---
use_default_settings: true

engines:
  - name: ahmia
    inactive: true
  - name: apple maps
    disabled: false
  - name: torch
    inactive: true

brand:
  public_instances: ""

general:
  debug: false
  instance_name: SearXNG

preferences:
  lock:
    - autocomplete
    - favicon_resolver
    - method

search:
  autocomplete: duckduckgo
  favicon_resolver: duckduckgo
  formats:
    - html
  safe_search: 1

server:
  # base_url: http://example.com/location # ${SEARXNG_BASE_URL}
  bind_address: 0.0.0.0
  http_protocol_version: !!str 1.1
  limiter: false
  method: GET
  # secret_key: ultrasecretkey # ${SEARXNG_SECRET}

plugins:
  searx.plugins.ahmia_filter.SXNGPlugin:
    active: false
  searx.plugins.calculator.SXNGPlugin:
    active: true
  searx.plugins.hash_plugin.SXNGPlugin:
    active: true
  searx.plugins.hostnames.SXNGPlugin:
    active: true
  searx.plugins.infinite_scroll.SXNGPlugin:
    active: false # TODO: true
  searx.plugins.oa_doi_rewrite.SXNGPlugin:
    active: true
  searx.plugins.self_info.SXNGPlugin:
    active: true
  searx.plugins.time_zone.SXNGPlugin:
    active: true
  searx.plugins.tor_check.SXNGPlugin:
    active: false
  searx.plugins.tracker_url_remover.SXNGPlugin:
    active: true
  searx.plugins.unit_converter.SXNGPlugin:
    active: true

hostnames:
  replace:
    (www\.)?instagram\.com$: imginn.com
    (www\.)?twitter\.com$: xcancel.com
    (www\.)?x\.com$: xcancel.com
