---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/fogejo
  - resources/sopssecret.yaml

configMapGenerator:
  - behavior: merge
    envs:
      - configs/fogejo-app-ini.env
    name: forgejo-app-ini-env
    namespace: forgejo

patches:
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - git.***REMOVED***
    target:
      kind: Certificate
      name: forgejo
      namespace: forgejo
  - patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`git.***REMOVED***`)
    target:
      kind: IngressRoute
      name: forgejo
      namespace: forgejo
