---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/rsshub
  # - resources/persistentvolume.yaml
  # - resources/persistentvolumeclaim.yaml

# secretGenerator:
#   - envs:
#       - configs/pds.env
#     name: pds-env
#     namespace: rsshub

patches:
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - rsshub.${DOMAIN_NAME}
    target:
      kind: Certificate
      name: rsshub
      namespace: rsshub
  - patch: |-
      - op: replace
        path: /spec/hostnames
        value:
          - rsshub.${DOMAIN_NAME}
    target:
      kind: HTTPRoute
      name: rsshub
      namespace: rsshub
