---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - gitea
  # - gitea-actions
  - llama-cpp
  - media-server
  - miasma
  # - pds
  - pocket-id
  - redirector
  - searxng
  - vaultwarden
