apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: gitea-admin
  namespace: gitea
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:q2uEDdFLjk75kLmA12qdfa4=,iv:73Kptwtiwd0hhCrYF7UwsBRHZPWugOLpEOlTGAeWOGM=,tag:P3TE9NG581Kp3afhblV5QA==,type:str]
      stringData:
        GITEA__OAUTH2__JWT_SECRET: ENC[AES256_GCM,data:J3bP+vazH1eWBSBUg/ysk4bW2flPVoUduS7OuzC6zX1aNPgw8zN+nfZDUg==,iv:RA2HYdhueroB8WBVeg4KLntWPTNuKK4OHErJGz9DjF0=,tag:ozb9ZAb2juI3cODeeJi1Yw==,type:str]
        GITEA__SECURITY__INTERNAL_TOKEN: ENC[AES256_GCM,data:0ciiC4ht0HvtTOUPP9xK8oOi0bqNEb2PC+J1K0XHU4l/m2nk0bwTxQdVaomyArZA20jcP8jexq84IJQUis9BoSXVk8j2+2wevWa1jzBetCqnYvbyMIOTe9AOB2xOTF/7m1de/rtZZuqV,iv:CqLyo3bvZvRilVbWcWo5t6ItA1/19B3wJGkiHdr8JjY=,tag:O4uJe59FcI5reww46zzmug==,type:str]
        GITEA__SECURITY__SECRET_KEY: ENC[AES256_GCM,data:LegHF8HwPQii52DuAbvNpd2bf6m0egfYfnxUT1BKbO35PqZHepKo1mfCPCgA7+5oBJugSjvR8y+mf6i61teGIQ==,iv:hN0ZceR/TcmVrXVek094ZmR2vbxhvRrYCou1wKhMKpY=,tag:341LGCfdNZPG30xeRWFI7g==,type:str]
        GITEA__SERVER__LFS_JWT_SECRET: ENC[AES256_GCM,data:aYmWCoIS9Cla/XbvuzrpZeGdLE9LD51e1qCNjSUucEB/IeS+yPcRBlXQmg==,iv:S4BphYmjmli5qhkzYBLHmESyj/SE5x9JOiwcn8tPf4U=,tag:6RRmv52Eu5p0O322emVMqA==,type:str]
    - name: ENC[AES256_GCM,data:6RnCG44V4w4lU8GQKw97xQ==,iv:GfVl5eeLvNCgjcq0KE8kxPlVsV9w0g5WJxF/M/I3BiE=,tag:slZB7trToJATC+WRO/5KVg==,type:str]
      stringData:
        GITEA_ADMIN_PASSWORD: ENC[AES256_GCM,data:9u/BtdUJMZYDa8J/ro889Q==,iv:O7iaLjtKs1WeyTI16sAqQN2Jh4EUhnNopMfwTY4B7eU=,tag:4n1k0+qFfYhIjlp5Aj459A==,type:str]
        GITEA_ADMIN_USERNAME: ENC[AES256_GCM,data:fDTgdmLxMHs9i80=,iv:M4WwzaK9AqOA5xCDi/DwdJV2RVzumblZw4mvipf3cD8=,tag:OGfXKiZqCCt3bdTmvkZ6sg==,type:str]
sops:
  age:
    - recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RFFsK2xlMUlDTklPUmVM
        RnJaaXZLTjh3VWZvVXhadFF4SXBOczNrV0M4Cmk3eVZDUStjb2JWM1gzaFFBeGFF
        clBpZU8xVTFrOVhnQTY4VCtDM3hkaTQKLS0tIDA3YjF1VDhLNkpXb2NsREJEMlRn
        UHJVb0w0SjkyY3pJcUJjMjNQVUJIdlkKr/iu2QIdmEsQBlPGgAJEDmfdC5GXiGHk
        NqWOaDJN5OLc69RChUmpngXuzLuXRGFfL6EqhBZUIw3EjxC85OMVkg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-14T08:14:48Z"
  mac: ENC[AES256_GCM,data:bGPHKzl8gDDioXC/Biq7OgNwGxtizR+t/W8EcW203AKmtGEvC37snkRpPGrxGjBO1LjX0z4oR/ycBlgQjnYaSa9L/wH7UENnAXpqgV4MhEEA586r78+sz0JooxOVCSMzoyJGEwrGtYAMYByDEpoVtPY0TugRXwzPdCj7V5eBpBM=,iv:yh4R+Em8kyRuJZ2i0r2m/9R2o3ksDqE/QqowsRNyRf4=,tag:gq742chnSUE+33hE8LOWsw==,type:str]
  encrypted_suffix: Templates
  version: 3.12.2
