apiVersion: v1
kind: Secret
metadata:
  name: runner
  namespace: gitea-actions
stringData:
  token: ENC[AES256_GCM,data:0o1VO4tmhf3nwUaQI9Afo3nP2q1r/wAd16quOmUUW8Q=,iv:mQS+gWPHZl37TxK4ERjKkruEm4bejf6nd26m0b557Po=,tag:3WdSL58ZucREAAYk4jGhZw==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM09IdnJEejNkQkZ3Yzh5
        SW05M1dQak5PRWN0eENIOGU3cEVBZ3VYNXhZCnIxV3FlcE9TdGZCdmlUWHJIK0p3
        bmtQWWhJVm9kM1o0NXM2dFlSS2xiME0KLS0tIHhDTlhEVFJuWXFSa0Jkd3h4Y2JP
        SzBDcTV5U0pzSFRxbTNCVElHVm1BVEkKdLFk1SONr7goJVo9XiyeNw4hFTZZIuQa
        bMCii8Umb4D48Ov7Yiv2y5yx7LZU7joYqdsvR8FvDvR8ks/MKyIoMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1cfvwwcvy3qj55kswlwymnvpwuwjymrp7xnjeycxma6qtdzv979qqd3kwue
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-13T18:19:31Z"
  mac: ENC[AES256_GCM,data:mPdepqP/imS7pVLg0E60kT+cgXifJSfxO0buT2yfop1XgT1IpPhdnBOkSSK1k8ksIrb4/sRdRaty7gI5cdUzNgXHJ4Q58ud9nbGbYbA6NAtuqA9Lsp4WMUOwbuqXPfnFwu1HDqU8g5gunlFHdIHn67lWT3Xd7OxPPKhoVkrw4K0=,iv:wUU9fnZUevekFJTh4oAeEDikGI2Oke+xlZ+HIlMHCsc=,tag:/LlAO8+14Oil5wPvREG0NQ==,type:str]
  version: 3.13.0
