---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/pocket-id

secretGenerator:
  - envs:
      - configs/pocket-id.env
    name: pocket-id-env
    namespace: pocket-id

patches:
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
          - login.${DOMAIN_NAME}
    target:
      kind: Certificate
      name: pocket-id
      namespace: pocket-id
  - patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`login.${DOMAIN_NAME}`)
    target:
      kind: IngressRoute
      name: pocket-id
      namespace: pocket-id
