---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: social
  namespace: social
spec:
  dnsNames:
    - social.example.com
  duration: 168h
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging # FIXME: letsencrypt
  privateKey:
    algorithm: ECDSA
    size: 256
  renewBefore: 8h
  secretName: social-tls
