---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: pocket-id
  namespace: pocket-id
spec:
  filterTags:
    extract: $version
    pattern: ^v(?P<version>\d+\.\d+\.\d+)-distroless$
  imageRepositoryRef:
    name: pocket-id
  policy:
    semver:
      range: ">=2.7.0 <3.0.0"
